export interface Option {
  label: string;
  value: string;
}

export const SUBJECT_CATEGORIES: Option[] = [
  { label: 'สุ่มทุกหมวด (All)', value: 'all' },
  { label: 'สิ่งมีชีวิตลี้ลับ/สัตว์ประหลาด', value: 'mythical_creatures' },
  { label: 'มนุษย์/ผู้ติดเชื้อแปลกประหลาด', value: 'fantasy_characters' },
  { label: 'สิ่งของ/ความผิดปกติทางฟิสิกส์', value: 'other' }
];

export const MYTHICAL_CREATURES: Option[] = [
  { label: 'สุ่มอัตโนมัติ (Random)', value: '' },
  { label: '1. ครีปเจอร์/สัตว์ประหลาด 1', value: 'deep-sea anomalous creature floating in the air dripping a highly reflective viscous black fluid' },
  { label: '2. ครีปเจอร์/สัตว์ประหลาด 2', value: 'floating spectral mass of shifting organic eyes with visible rotting muscle fibers' },
  { label: '3. ครีปเจอร์/สัตว์ประหลาด 3', value: 'massive pale skinwalker caught mid-transformation wearing the torn remnants of hiking gear' },
  { label: '4. ครีปเจอร์/สัตว์ประหลาด 4', value: 'hyper-realistic Wendigo-like entity with a head that resembles a rusted satellite dish' },
  { label: '5. ครีปเจอร์/สัตว์ประหลาด 5', value: 'deep-sea anomalous creature floating in the air wearing the torn remnants of hiking gear' },
  { label: '6. ครีปเจอร์/สัตว์ประหลาด 6', value: 'hyper-realistic Wendigo-like entity whose physical presence is bending the air like intense heat' },
  { label: '7. ครีปเจอร์/สัตว์ประหลาด 7', value: 'bipedal reptilian cryptid covered in swamp mud emitting a bio-luminescent sickly green glow from deep within' },
  { label: '8. ครีปเจอร์/สัตว์ประหลาด 8', value: 'lovecraftian appendage breaking through the floor wearing the torn remnants of hiking gear' },
  { label: '9. ครีปเจอร์/สัตว์ประหลาด 9', value: 'bipedal reptilian cryptid covered in swamp mud with its entire ribcage seemingly turned completely inside out' },
  { label: '10. ครีปเจอร์/สัตว์ประหลาด 10', value: 'lovecraftian appendage breaking through the floor with its entire ribcage seemingly turned completely inside out' },
  { label: '11. ครีปเจอร์/สัตว์ประหลาด 11', value: 'bipedal reptilian cryptid covered in swamp mud with visible rotting muscle fibers' },
  { label: '12. ครีปเจอร์/สัตว์ประหลาด 12', value: 'bipedal reptilian cryptid covered in swamp mud wearing the torn remnants of hiking gear' },
  { label: '13. ครีปเจอร์/สัตว์ประหลาด 13', value: 'distorted humanoid with limbs 10 feet long with mathematically perfect geometric fractal skin' },
  { label: '14. ครีปเจอร์/สัตว์ประหลาด 14', value: 'hyper-realistic Wendigo-like entity surrounded by a localized swarm of massive flies' },
  { label: '15. ครีปเจอร์/สัตว์ประหลาด 15', value: 'massive pale skinwalker caught mid-transformation with mathematically perfect geometric fractal skin' },
  { label: '16. ครีปเจอร์/สัตว์ประหลาด 16', value: 'massive pale skinwalker caught mid-transformation moving in a deeply unsettling stop-motion judder' },
  { label: '17. ครีปเจอร์/สัตว์ประหลาด 17', value: 'floating spectral mass of shifting organic eyes with a head that resembles a rusted satellite dish' },
  { label: '18. ครีปเจอร์/สัตว์ประหลาด 18', value: 'deep-sea anomalous creature floating in the air with mathematically perfect geometric fractal skin' },
  { label: '19. ครีปเจอร์/สัตว์ประหลาด 19', value: 'floating spectral mass of shifting organic eyes with mathematically perfect geometric fractal skin' },
  { label: '20. ครีปเจอร์/สัตว์ประหลาด 20', value: 'massive pale skinwalker caught mid-transformation with a head that resembles a rusted satellite dish' },
  { label: '21. ครีปเจอร์/สัตว์ประหลาด 21', value: 'colossal shadow entity that absorbs all light with mathematically perfect geometric fractal skin' },
  { label: '22. ครีปเจอร์/สัตว์ประหลาด 22', value: 'distorted humanoid with limbs 10 feet long dripping a highly reflective viscous black fluid' },
  { label: '23. ครีปเจอร์/สัตว์ประหลาด 23', value: 'massive pale skinwalker caught mid-transformation surrounded by a localized swarm of massive flies' },
  { label: '24. ครีปเจอร์/สัตว์ประหลาด 24', value: 'floating spectral mass of shifting organic eyes moving in a deeply unsettling stop-motion judder' },
  { label: '25. ครีปเจอร์/สัตว์ประหลาด 25', value: 'floating spectral mass of shifting organic eyes with its entire ribcage seemingly turned completely inside out' },
  { label: '26. ครีปเจอร์/สัตว์ประหลาด 26', value: 'bipedal reptilian cryptid covered in swamp mud whose physical presence is bending the air like intense heat' },
  { label: '27. ครีปเจอร์/สัตว์ประหลาด 27', value: 'distorted humanoid with limbs 10 feet long wearing the torn remnants of hiking gear' },
  { label: '28. ครีปเจอร์/สัตว์ประหลาด 28', value: 'distorted humanoid with limbs 10 feet long moving in a deeply unsettling stop-motion judder' },
  { label: '29. ครีปเจอร์/สัตว์ประหลาด 29', value: 'deep-sea anomalous creature floating in the air whose physical presence is bending the air like intense heat' },
  { label: '30. ครีปเจอร์/สัตว์ประหลาด 30', value: 'bipedal reptilian cryptid covered in swamp mud with mathematically perfect geometric fractal skin' },
  { label: '31. ครีปเจอร์/สัตว์ประหลาด 31', value: 'lovecraftian appendage breaking through the floor with mathematically perfect geometric fractal skin' },
  { label: '32. ครีปเจอร์/สัตว์ประหลาด 32', value: 'deep-sea anomalous creature floating in the air moving in a deeply unsettling stop-motion judder' },
  { label: '33. ครีปเจอร์/สัตว์ประหลาด 33', value: 'hyper-realistic Wendigo-like entity dripping a highly reflective viscous black fluid' },
  { label: '34. ครีปเจอร์/สัตว์ประหลาด 34', value: 'hyper-realistic Wendigo-like entity with mathematically perfect geometric fractal skin' },
  { label: '35. ครีปเจอร์/สัตว์ประหลาด 35', value: 'colossal shadow entity that absorbs all light surrounded by a localized swarm of massive flies' },
  { label: '36. ครีปเจอร์/สัตว์ประหลาด 36', value: 'distorted humanoid with limbs 10 feet long with its entire ribcage seemingly turned completely inside out' },
  { label: '37. ครีปเจอร์/สัตว์ประหลาด 37', value: 'bipedal reptilian cryptid covered in swamp mud dripping a highly reflective viscous black fluid' },
  { label: '38. ครีปเจอร์/สัตว์ประหลาด 38', value: 'floating spectral mass of shifting organic eyes emitting a bio-luminescent sickly green glow from deep within' },
  { label: '39. ครีปเจอร์/สัตว์ประหลาด 39', value: 'distorted humanoid with limbs 10 feet long with visible rotting muscle fibers' },
  { label: '40. ครีปเจอร์/สัตว์ประหลาด 40', value: 'floating spectral mass of shifting organic eyes dripping a highly reflective viscous black fluid' },
  { label: '41. ครีปเจอร์/สัตว์ประหลาด 41', value: 'deep-sea anomalous creature floating in the air emitting a bio-luminescent sickly green glow from deep within' },
  { label: '42. ครีปเจอร์/สัตว์ประหลาด 42', value: 'massive pale skinwalker caught mid-transformation emitting a bio-luminescent sickly green glow from deep within' },
  { label: '43. ครีปเจอร์/สัตว์ประหลาด 43', value: 'colossal shadow entity that absorbs all light wearing the torn remnants of hiking gear' },
  { label: '44. ครีปเจอร์/สัตว์ประหลาด 44', value: 'hyper-realistic Wendigo-like entity moving in a deeply unsettling stop-motion judder' },
  { label: '45. ครีปเจอร์/สัตว์ประหลาด 45', value: 'lovecraftian appendage breaking through the floor whose physical presence is bending the air like intense heat' },
  { label: '46. ครีปเจอร์/สัตว์ประหลาด 46', value: 'bipedal reptilian cryptid covered in swamp mud surrounded by a localized swarm of massive flies' },
  { label: '47. ครีปเจอร์/สัตว์ประหลาด 47', value: 'massive pale skinwalker caught mid-transformation with visible rotting muscle fibers' },
  { label: '48. ครีปเจอร์/สัตว์ประหลาด 48', value: 'colossal shadow entity that absorbs all light dripping a highly reflective viscous black fluid' },
  { label: '49. ครีปเจอร์/สัตว์ประหลาด 49', value: 'distorted humanoid with limbs 10 feet long whose physical presence is bending the air like intense heat' },
  { label: '50. ครีปเจอร์/สัตว์ประหลาด 50', value: 'hyper-realistic Wendigo-like entity with visible rotting muscle fibers' },
  { label: '51. ครีปเจอร์/สัตว์ประหลาด 51', value: 'deep-sea anomalous creature floating in the air surrounded by a localized swarm of massive flies' },
  { label: '52. ครีปเจอร์/สัตว์ประหลาด 52', value: 'colossal shadow entity that absorbs all light with visible rotting muscle fibers' },
  { label: '53. ครีปเจอร์/สัตว์ประหลาด 53', value: 'colossal shadow entity that absorbs all light emitting a bio-luminescent sickly green glow from deep within' },
  { label: '54. ครีปเจอร์/สัตว์ประหลาด 54', value: 'bipedal reptilian cryptid covered in swamp mud moving in a deeply unsettling stop-motion judder' },
  { label: '55. ครีปเจอร์/สัตว์ประหลาด 55', value: 'distorted humanoid with limbs 10 feet long surrounded by a localized swarm of massive flies' },
  { label: '56. ครีปเจอร์/สัตว์ประหลาด 56', value: 'floating spectral mass of shifting organic eyes surrounded by a localized swarm of massive flies' },
  { label: '57. ครีปเจอร์/สัตว์ประหลาด 57', value: 'lovecraftian appendage breaking through the floor with visible rotting muscle fibers' },
  { label: '58. ครีปเจอร์/สัตว์ประหลาด 58', value: 'hyper-realistic Wendigo-like entity wearing the torn remnants of hiking gear' },
  { label: '59. ครีปเจอร์/สัตว์ประหลาด 59', value: 'colossal shadow entity that absorbs all light whose physical presence is bending the air like intense heat' },
  { label: '60. ครีปเจอร์/สัตว์ประหลาด 60', value: 'hyper-realistic Wendigo-like entity emitting a bio-luminescent sickly green glow from deep within' },
  { label: '61. ครีปเจอร์/สัตว์ประหลาด 61', value: 'deep-sea anomalous creature floating in the air with a head that resembles a rusted satellite dish' },
  { label: '62. ครีปเจอร์/สัตว์ประหลาด 62', value: 'massive pale skinwalker caught mid-transformation with its entire ribcage seemingly turned completely inside out' },
  { label: '63. ครีปเจอร์/สัตว์ประหลาด 63', value: 'lovecraftian appendage breaking through the floor surrounded by a localized swarm of massive flies' },
  { label: '64. ครีปเจอร์/สัตว์ประหลาด 64', value: 'colossal shadow entity that absorbs all light with a head that resembles a rusted satellite dish' },
  { label: '65. ครีปเจอร์/สัตว์ประหลาด 65', value: 'bipedal reptilian cryptid covered in swamp mud with a head that resembles a rusted satellite dish' },
  { label: '66. ครีปเจอร์/สัตว์ประหลาด 66', value: 'distorted humanoid with limbs 10 feet long with a head that resembles a rusted satellite dish' },
  { label: '67. ครีปเจอร์/สัตว์ประหลาด 67', value: 'deep-sea anomalous creature floating in the air with visible rotting muscle fibers' },
  { label: '68. ครีปเจอร์/สัตว์ประหลาด 68', value: 'hyper-realistic Wendigo-like entity with its entire ribcage seemingly turned completely inside out' },
  { label: '69. ครีปเจอร์/สัตว์ประหลาด 69', value: 'massive pale skinwalker caught mid-transformation dripping a highly reflective viscous black fluid' },
  { label: '70. ครีปเจอร์/สัตว์ประหลาด 70', value: 'colossal shadow entity that absorbs all light with its entire ribcage seemingly turned completely inside out' },
  { label: '71. ครีปเจอร์/สัตว์ประหลาด 71', value: 'deep-sea anomalous creature floating in the air with its entire ribcage seemingly turned completely inside out' },
  { label: '72. ครีปเจอร์/สัตว์ประหลาด 72', value: 'lovecraftian appendage breaking through the floor dripping a highly reflective viscous black fluid' },
  { label: '73. ครีปเจอร์/สัตว์ประหลาด 73', value: 'floating spectral mass of shifting organic eyes wearing the torn remnants of hiking gear' },
  { label: '74. ครีปเจอร์/สัตว์ประหลาด 74', value: 'massive pale skinwalker caught mid-transformation whose physical presence is bending the air like intense heat' },
  { label: '75. ครีปเจอร์/สัตว์ประหลาด 75', value: 'lovecraftian appendage breaking through the floor moving in a deeply unsettling stop-motion judder' },
  { label: '76. ครีปเจอร์/สัตว์ประหลาด 76', value: 'distorted humanoid with limbs 10 feet long emitting a bio-luminescent sickly green glow from deep within' },
  { label: '77. ครีปเจอร์/สัตว์ประหลาด 77', value: 'colossal shadow entity that absorbs all light moving in a deeply unsettling stop-motion judder' },
  { label: '78. ครีปเจอร์/สัตว์ประหลาด 78', value: 'floating spectral mass of shifting organic eyes whose physical presence is bending the air like intense heat' },
  { label: '79. ครีปเจอร์/สัตว์ประหลาด 79', value: 'lovecraftian appendage breaking through the floor with a head that resembles a rusted satellite dish' },
  { label: '80. ครีปเจอร์/สัตว์ประหลาด 80', value: 'lovecraftian appendage breaking through the floor emitting a bio-luminescent sickly green glow from deep within' },
  { label: '81. ครีปเจอร์/สัตว์ประหลาด 81', value: 'deep-sea anomalous creature floating in the air wearing the torn remnants of hiking gear' },
  { label: '82. ครีปเจอร์/สัตว์ประหลาด 82', value: 'hyper-realistic Wendigo-like entity dripping a highly reflective viscous black fluid' },
  { label: '83. ครีปเจอร์/สัตว์ประหลาด 83', value: 'colossal shadow entity that absorbs all light with a head that resembles a rusted satellite dish' },
  { label: '84. ครีปเจอร์/สัตว์ประหลาด 84', value: 'hyper-realistic Wendigo-like entity surrounded by a localized swarm of massive flies' },
  { label: '85. ครีปเจอร์/สัตว์ประหลาด 85', value: 'hyper-realistic Wendigo-like entity whose physical presence is bending the air like intense heat' },
  { label: '86. ครีปเจอร์/สัตว์ประหลาด 86', value: 'lovecraftian appendage breaking through the floor with visible rotting muscle fibers' },
  { label: '87. ครีปเจอร์/สัตว์ประหลาด 87', value: 'hyper-realistic Wendigo-like entity whose physical presence is bending the air like intense heat' },
  { label: '88. ครีปเจอร์/สัตว์ประหลาด 88', value: 'deep-sea anomalous creature floating in the air wearing the torn remnants of hiking gear' },
  { label: '89. ครีปเจอร์/สัตว์ประหลาด 89', value: 'bipedal reptilian cryptid covered in swamp mud wearing the torn remnants of hiking gear' },
  { label: '90. ครีปเจอร์/สัตว์ประหลาด 90', value: 'distorted humanoid with limbs 10 feet long with visible rotting muscle fibers' },
  { label: '91. ครีปเจอร์/สัตว์ประหลาด 91', value: 'massive pale skinwalker caught mid-transformation with its entire ribcage seemingly turned completely inside out' },
  { label: '92. ครีปเจอร์/สัตว์ประหลาด 92', value: 'distorted humanoid with limbs 10 feet long emitting a bio-luminescent sickly green glow from deep within' },
  { label: '93. ครีปเจอร์/สัตว์ประหลาด 93', value: 'hyper-realistic Wendigo-like entity whose physical presence is bending the air like intense heat' },
  { label: '94. ครีปเจอร์/สัตว์ประหลาด 94', value: 'colossal shadow entity that absorbs all light with a head that resembles a rusted satellite dish' },
  { label: '95. ครีปเจอร์/สัตว์ประหลาด 95', value: 'distorted humanoid with limbs 10 feet long emitting a bio-luminescent sickly green glow from deep within' },
  { label: '96. ครีปเจอร์/สัตว์ประหลาด 96', value: 'hyper-realistic Wendigo-like entity with a head that resembles a rusted satellite dish' },
  { label: '97. ครีปเจอร์/สัตว์ประหลาด 97', value: 'bipedal reptilian cryptid covered in swamp mud wearing the torn remnants of hiking gear' },
  { label: '98. ครีปเจอร์/สัตว์ประหลาด 98', value: 'deep-sea anomalous creature floating in the air wearing the torn remnants of hiking gear' },
  { label: '99. ครีปเจอร์/สัตว์ประหลาด 99', value: 'colossal shadow entity that absorbs all light with its entire ribcage seemingly turned completely inside out' },
  { label: '100. ครีปเจอร์/สัตว์ประหลาด 100', value: 'hyper-realistic Wendigo-like entity whose physical presence is bending the air like intense heat' },
  { label: 'ระบุเอง (Custom)', value: 'custom' }
];

export const FANTASY_CHARACTERS: Option[] = [
  { label: 'สุ่มอัตโนมัติ (Random)', value: '' },
  { label: '1. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 1', value: 'mutated miner fused permanently with large crystalline structures who is silently screaming directly at the lens' },
  { label: '2. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 2', value: 'feral child running with the exact posture of a spider with wildly glowing iridescent silver veins under their skin' },
  { label: '3. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 3', value: 'floating cultist draped in impossibly heavy iron chains who appears to be lagging behind reality by half a second' },
  { label: '4. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 4', value: 'floating cultist draped in impossibly heavy iron chains whose shadow is moving completely independently of their body' },
  { label: '5. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 5', value: 'feral child running with the exact posture of a spider who is twisting their limbs into anatomically impossible angles' },
  { label: '6. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 6', value: 'bio-mechanically augmented soldier leaking synthetic white blood who is silently screaming directly at the lens' },
  { label: '7. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 7', value: 'translucent ghost-like woman with hyper-detailed weeping skin who is crying thick drops of molten gold that burn the floor' },
  { label: '8. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 8', value: 'translucent ghost-like woman with hyper-detailed weeping skin who is twisting their limbs into anatomically impossible angles' },
  { label: '9. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 9', value: 'feral child running with the exact posture of a spider who is physically dissolving into pixels of pure physical light' },
  { label: '10. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 10', value: 'translucent ghost-like woman with hyper-detailed weeping skin whose shadow is moving completely independently of their body' },
  { label: '11. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 11', value: 'translucent ghost-like woman with hyper-detailed weeping skin who is silently screaming directly at the lens' },
  { label: '12. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 12', value: 'mutated miner fused permanently with large crystalline structures who is leaving perfect scorch marks with every single footstep' },
  { label: '13. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 13', value: 'patient in a hospital gown whose face is a smooth blank void whose body temperature is visibly freezing the breath in the air' },
  { label: '14. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 14', value: 'urban explorer who has physically grown into the concrete wall who is physically dissolving into pixels of pure physical light' },
  { label: '15. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 15', value: 'patient in a hospital gown whose face is a smooth blank void who appears to be lagging behind reality by half a second' },
  { label: '16. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 16', value: 'urban explorer who has physically grown into the concrete wall who is twisting their limbs into anatomically impossible angles' },
  { label: '17. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 17', value: 'floating cultist draped in impossibly heavy iron chains whose body temperature is visibly freezing the breath in the air' },
  { label: '18. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 18', value: 'patient in a hospital gown whose face is a smooth blank void who is crying thick drops of molten gold that burn the floor' },
  { label: '19. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 19', value: 'translucent ghost-like woman with hyper-detailed weeping skin who is physically dissolving into pixels of pure physical light' },
  { label: '20. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 20', value: 'unnervingly still person wearing an outdated 1950s gas mask who is twisting their limbs into anatomically impossible angles' },
  { label: '21. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 21', value: 'unnervingly still person wearing an outdated 1950s gas mask whose eyes are replaced by deep, physically accurate black holes' },
  { label: '22. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 22', value: 'bio-mechanically augmented soldier leaking synthetic white blood whose eyes are replaced by deep, physically accurate black holes' },
  { label: '23. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 23', value: 'mutated miner fused permanently with large crystalline structures whose eyes are replaced by deep, physically accurate black holes' },
  { label: '24. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 24', value: 'translucent ghost-like woman with hyper-detailed weeping skin with wildly glowing iridescent silver veins under their skin' },
  { label: '25. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 25', value: 'feral child running with the exact posture of a spider whose body temperature is visibly freezing the breath in the air' },
  { label: '26. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 26', value: 'unnervingly still person wearing an outdated 1950s gas mask whose shadow is moving completely independently of their body' },
  { label: '27. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 27', value: 'translucent ghost-like woman with hyper-detailed weeping skin whose body temperature is visibly freezing the breath in the air' },
  { label: '28. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 28', value: 'mutated miner fused permanently with large crystalline structures who is physically dissolving into pixels of pure physical light' },
  { label: '29. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 29', value: 'unnervingly still person wearing an outdated 1950s gas mask with wildly glowing iridescent silver veins under their skin' },
  { label: '30. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 30', value: 'patient in a hospital gown whose face is a smooth blank void who is twisting their limbs into anatomically impossible angles' },
  { label: '31. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 31', value: 'unnervingly still person wearing an outdated 1950s gas mask who is leaving perfect scorch marks with every single footstep' },
  { label: '32. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 32', value: 'patient in a hospital gown whose face is a smooth blank void whose eyes are replaced by deep, physically accurate black holes' },
  { label: '33. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 33', value: 'mutated miner fused permanently with large crystalline structures who is twisting their limbs into anatomically impossible angles' },
  { label: '34. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 34', value: 'bio-mechanically augmented soldier leaking synthetic white blood who is twisting their limbs into anatomically impossible angles' },
  { label: '35. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 35', value: 'feral child running with the exact posture of a spider who appears to be lagging behind reality by half a second' },
  { label: '36. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 36', value: 'unnervingly still person wearing an outdated 1950s gas mask whose body temperature is visibly freezing the breath in the air' },
  { label: '37. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 37', value: 'feral child running with the exact posture of a spider whose eyes are replaced by deep, physically accurate black holes' },
  { label: '38. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 38', value: 'urban explorer who has physically grown into the concrete wall who is leaving perfect scorch marks with every single footstep' },
  { label: '39. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 39', value: 'urban explorer who has physically grown into the concrete wall whose body temperature is visibly freezing the breath in the air' },
  { label: '40. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 40', value: 'mutated miner fused permanently with large crystalline structures who appears to be lagging behind reality by half a second' },
  { label: '41. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 41', value: 'floating cultist draped in impossibly heavy iron chains who is twisting their limbs into anatomically impossible angles' },
  { label: '42. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 42', value: 'floating cultist draped in impossibly heavy iron chains who is physically dissolving into pixels of pure physical light' },
  { label: '43. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 43', value: 'patient in a hospital gown whose face is a smooth blank void who is silently screaming directly at the lens' },
  { label: '44. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 44', value: 'unnervingly still person wearing an outdated 1950s gas mask who is physically dissolving into pixels of pure physical light' },
  { label: '45. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 45', value: 'patient in a hospital gown whose face is a smooth blank void who is physically dissolving into pixels of pure physical light' },
  { label: '46. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 46', value: 'patient in a hospital gown whose face is a smooth blank void whose shadow is moving completely independently of their body' },
  { label: '47. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 47', value: 'bio-mechanically augmented soldier leaking synthetic white blood who is crying thick drops of molten gold that burn the floor' },
  { label: '48. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 48', value: 'translucent ghost-like woman with hyper-detailed weeping skin whose eyes are replaced by deep, physically accurate black holes' },
  { label: '49. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 49', value: 'mutated miner fused permanently with large crystalline structures whose shadow is moving completely independently of their body' },
  { label: '50. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 50', value: 'floating cultist draped in impossibly heavy iron chains with wildly glowing iridescent silver veins under their skin' },
  { label: '51. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 51', value: 'unnervingly still person wearing an outdated 1950s gas mask who is silently screaming directly at the lens' },
  { label: '52. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 52', value: 'mutated miner fused permanently with large crystalline structures whose body temperature is visibly freezing the breath in the air' },
  { label: '53. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 53', value: 'urban explorer who has physically grown into the concrete wall whose eyes are replaced by deep, physically accurate black holes' },
  { label: '54. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 54', value: 'bio-mechanically augmented soldier leaking synthetic white blood with wildly glowing iridescent silver veins under their skin' },
  { label: '55. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 55', value: 'feral child running with the exact posture of a spider who is silently screaming directly at the lens' },
  { label: '56. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 56', value: 'feral child running with the exact posture of a spider who is crying thick drops of molten gold that burn the floor' },
  { label: '57. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 57', value: 'unnervingly still person wearing an outdated 1950s gas mask who is crying thick drops of molten gold that burn the floor' },
  { label: '58. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 58', value: 'translucent ghost-like woman with hyper-detailed weeping skin who appears to be lagging behind reality by half a second' },
  { label: '59. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 59', value: 'mutated miner fused permanently with large crystalline structures with wildly glowing iridescent silver veins under their skin' },
  { label: '60. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 60', value: 'urban explorer who has physically grown into the concrete wall who appears to be lagging behind reality by half a second' },
  { label: '61. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 61', value: 'urban explorer who has physically grown into the concrete wall who is crying thick drops of molten gold that burn the floor' },
  { label: '62. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 62', value: 'mutated miner fused permanently with large crystalline structures who is crying thick drops of molten gold that burn the floor' },
  { label: '63. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 63', value: 'bio-mechanically augmented soldier leaking synthetic white blood who is physically dissolving into pixels of pure physical light' },
  { label: '64. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 64', value: 'urban explorer who has physically grown into the concrete wall who is silently screaming directly at the lens' },
  { label: '65. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 65', value: 'urban explorer who has physically grown into the concrete wall with wildly glowing iridescent silver veins under their skin' },
  { label: '66. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 66', value: 'translucent ghost-like woman with hyper-detailed weeping skin who is leaving perfect scorch marks with every single footstep' },
  { label: '67. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 67', value: 'bio-mechanically augmented soldier leaking synthetic white blood whose body temperature is visibly freezing the breath in the air' },
  { label: '68. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 68', value: 'floating cultist draped in impossibly heavy iron chains whose eyes are replaced by deep, physically accurate black holes' },
  { label: '69. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 69', value: 'feral child running with the exact posture of a spider whose shadow is moving completely independently of their body' },
  { label: '70. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 70', value: 'patient in a hospital gown whose face is a smooth blank void who is leaving perfect scorch marks with every single footstep' },
  { label: '71. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 71', value: 'floating cultist draped in impossibly heavy iron chains who is silently screaming directly at the lens' },
  { label: '72. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 72', value: 'urban explorer who has physically grown into the concrete wall whose shadow is moving completely independently of their body' },
  { label: '73. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 73', value: 'bio-mechanically augmented soldier leaking synthetic white blood who appears to be lagging behind reality by half a second' },
  { label: '74. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 74', value: 'bio-mechanically augmented soldier leaking synthetic white blood whose shadow is moving completely independently of their body' },
  { label: '75. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 75', value: 'unnervingly still person wearing an outdated 1950s gas mask who appears to be lagging behind reality by half a second' },
  { label: '76. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 76', value: 'feral child running with the exact posture of a spider who is leaving perfect scorch marks with every single footstep' },
  { label: '77. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 77', value: 'floating cultist draped in impossibly heavy iron chains who is leaving perfect scorch marks with every single footstep' },
  { label: '78. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 78', value: 'bio-mechanically augmented soldier leaking synthetic white blood who is leaving perfect scorch marks with every single footstep' },
  { label: '79. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 79', value: 'patient in a hospital gown whose face is a smooth blank void with wildly glowing iridescent silver veins under their skin' },
  { label: '80. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 80', value: 'floating cultist draped in impossibly heavy iron chains who is crying thick drops of molten gold that burn the floor' },
  { label: '81. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 81', value: 'feral child running with the exact posture of a spider whose eyes are replaced by deep, physically accurate black holes' },
  { label: '82. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 82', value: 'patient in a hospital gown whose face is a smooth blank void with wildly glowing iridescent silver veins under their skin' },
  { label: '83. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 83', value: 'unnervingly still person wearing an outdated 1950s gas mask whose shadow is moving completely independently of their body' },
  { label: '84. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 84', value: 'feral child running with the exact posture of a spider who appears to be lagging behind reality by half a second' },
  { label: '85. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 85', value: 'patient in a hospital gown whose face is a smooth blank void with wildly glowing iridescent silver veins under their skin' },
  { label: '86. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 86', value: 'unnervingly still person wearing an outdated 1950s gas mask whose shadow is moving completely independently of their body' },
  { label: '87. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 87', value: 'translucent ghost-like woman with hyper-detailed weeping skin who is physically dissolving into pixels of pure physical light' },
  { label: '88. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 88', value: 'translucent ghost-like woman with hyper-detailed weeping skin who is leaving perfect scorch marks with every single footstep' },
  { label: '89. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 89', value: 'patient in a hospital gown whose face is a smooth blank void who is leaving perfect scorch marks with every single footstep' },
  { label: '90. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 90', value: 'urban explorer who has physically grown into the concrete wall whose shadow is moving completely independently of their body' },
  { label: '91. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 91', value: 'urban explorer who has physically grown into the concrete wall who is leaving perfect scorch marks with every single footstep' },
  { label: '92. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 92', value: 'patient in a hospital gown whose face is a smooth blank void whose body temperature is visibly freezing the breath in the air' },
  { label: '93. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 93', value: 'mutated miner fused permanently with large crystalline structures whose shadow is moving completely independently of their body' },
  { label: '94. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 94', value: 'feral child running with the exact posture of a spider whose shadow is moving completely independently of their body' },
  { label: '95. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 95', value: 'unnervingly still person wearing an outdated 1950s gas mask who is twisting their limbs into anatomically impossible angles' },
  { label: '96. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 96', value: 'translucent ghost-like woman with hyper-detailed weeping skin who is silently screaming directly at the lens' },
  { label: '97. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 97', value: 'translucent ghost-like woman with hyper-detailed weeping skin who is leaving perfect scorch marks with every single footstep' },
  { label: '98. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 98', value: 'feral child running with the exact posture of a spider who is physically dissolving into pixels of pure physical light' },
  { label: '99. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 99', value: 'unnervingly still person wearing an outdated 1950s gas mask who is leaving perfect scorch marks with every single footstep' },
  { label: '100. มนุษย์ผิดปกติ/ผู้คุ้มคลั่ง 100', value: 'mutated miner fused permanently with large crystalline structures whose shadow is moving completely independently of their body' },
  { label: 'ระบุเอง (Custom)', value: 'custom' }
];

export const OTHER_SUBJECTS: Option[] = [
  { label: 'สุ่มอัตโนมัติ (Random)', value: '' },
  { label: '1. วัตถุอาถรรพ์/ฟิสิกส์พัง 1', value: 'door standing alone in an open field, leaking a blinding blue light that emits a low-frequency hum causing the camera sensor to vibrate' },
  { label: '2. วัตถุอาถรรพ์/ฟิสิกส์พัง 2', value: 'perfectly spherical singularity consuming dust particles that screams with a human voice whenever light touches it' },
  { label: '3. วัตถุอาถรรพ์/ฟิสิกส์พัง 3', value: 'refrigerator containing a pulsing fleshy core that is slowly, organically consuming the concrete around it' },
  { label: '4. วัตถุอาถรรพ์/ฟิสิกส์พัง 4', value: 'massive geometric obsidian monolith hovering silently that radiates intense waves of visual heat distortion' },
  { label: '5. วัตถุอาถรรพ์/ฟิสิกส์พัง 5', value: 'rusted 1970s sedan that is organically breathing that screams with a human voice whenever light touches it' },
  { label: '6. วัตถุอาถรรพ์/ฟิสิกส์พัง 6', value: 'rusted 1970s sedan that is organically breathing that renders all nearby shadows in the wrong direction' },
  { label: '7. วัตถุอาถรรพ์/ฟิสิกส์พัง 7', value: 'refrigerator containing a pulsing fleshy core that renders all nearby shadows in the wrong direction' },
  { label: '8. วัตถุอาถรรพ์/ฟิสิกส์พัง 8', value: 'rusted 1970s sedan that is organically breathing that leaves a trail of frozen ice on any surface it touches' },
  { label: '9. วัตถุอาถรรพ์/ฟิสิกส์พัง 9', value: 'door standing alone in an open field, leaking a blinding blue light that leaves a trail of frozen ice on any surface it touches' },
  { label: '10. วัตถุอาถรรพ์/ฟิสิกส์พัง 10', value: 'rusted 1970s sedan that is organically breathing that flickers between existence and violent static every 2 seconds' },
  { label: '11. วัตถุอาถรรพ์/ฟิสิกส์พัง 11', value: 'refrigerator containing a pulsing fleshy core that radiates intense waves of visual heat distortion' },
  { label: '12. วัตถุอาถรรพ์/ฟิสิกส์พัง 12', value: 'refrigerator containing a pulsing fleshy core that emits a low-frequency hum causing the camera sensor to vibrate' },
  { label: '13. วัตถุอาถรรพ์/ฟิสิกส์พัง 13', value: 'door standing alone in an open field, leaking a blinding blue light that radiates intense waves of visual heat distortion' },
  { label: '14. วัตถุอาถรรพ์/ฟิสิกส์พัง 14', value: 'vending machine deep in the woods filled with human bones that is slowly, organically consuming the concrete around it' },
  { label: '15. วัตถุอาถรรพ์/ฟิสิกส์พัง 15', value: 'television set broadcasting a hyper-realistic feed of the cameraman\'s future that flickers between existence and violent static every 2 seconds' },
  { label: '16. วัตถุอาถรรพ์/ฟิสิกส์พัง 16', value: 'child\'s toy robot that exhibits terrifyingly advanced AI movements that completely defies gravity within a 10-foot radius' },
  { label: '17. วัตถุอาถรรพ์/ฟิสิกส์พัง 17', value: 'door standing alone in an open field, leaking a blinding blue light that flickers between existence and violent static every 2 seconds' },
  { label: '18. วัตถุอาถรรพ์/ฟิสิกส์พัง 18', value: 'perfectly spherical singularity consuming dust particles that flickers between existence and violent static every 2 seconds' },
  { label: '19. วัตถุอาถรรพ์/ฟิสิกส์พัง 19', value: 'television set broadcasting a hyper-realistic feed of the cameraman\'s future that mirrors its environment with 100% physically accurate ray-tracing' },
  { label: '20. วัตถุอาถรรพ์/ฟิสิกส์พัง 20', value: 'television set broadcasting a hyper-realistic feed of the cameraman\'s future that is slowly, organically consuming the concrete around it' },
  { label: '21. วัตถุอาถรรพ์/ฟิสิกส์พัง 21', value: 'perfectly spherical singularity consuming dust particles that completely defies gravity within a 10-foot radius' },
  { label: '22. วัตถุอาถรรพ์/ฟิสิกส์พัง 22', value: 'child\'s toy robot that exhibits terrifyingly advanced AI movements that is slowly, organically consuming the concrete around it' },
  { label: '23. วัตถุอาถรรพ์/ฟิสิกส์พัง 23', value: 'perfectly spherical singularity consuming dust particles that radiates intense waves of visual heat distortion' },
  { label: '24. วัตถุอาถรรพ์/ฟิสิกส์พัง 24', value: 'refrigerator containing a pulsing fleshy core that mirrors its environment with 100% physically accurate ray-tracing' },
  { label: '25. วัตถุอาถรรพ์/ฟิสิกส์พัง 25', value: 'door standing alone in an open field, leaking a blinding blue light that is slowly, organically consuming the concrete around it' },
  { label: '26. วัตถุอาถรรพ์/ฟิสิกส์พัง 26', value: 'perfectly spherical singularity consuming dust particles that dissolves nearby objects into geometric dust instantly' },
  { label: '27. วัตถุอาถรรพ์/ฟิสิกส์พัง 27', value: 'rusted 1970s sedan that is organically breathing that is slowly, organically consuming the concrete around it' },
  { label: '28. วัตถุอาถรรพ์/ฟิสิกส์พัง 28', value: 'rusted 1970s sedan that is organically breathing that radiates intense waves of visual heat distortion' },
  { label: '29. วัตถุอาถรรพ์/ฟิสิกส์พัง 29', value: 'vending machine deep in the woods filled with human bones that completely defies gravity within a 10-foot radius' },
  { label: '30. วัตถุอาถรรพ์/ฟิสิกส์พัง 30', value: 'vending machine deep in the woods filled with human bones that radiates intense waves of visual heat distortion' },
  { label: '31. วัตถุอาถรรพ์/ฟิสิกส์พัง 31', value: 'door standing alone in an open field, leaking a blinding blue light that dissolves nearby objects into geometric dust instantly' },
  { label: '32. วัตถุอาถรรพ์/ฟิสิกส์พัง 32', value: 'television set broadcasting a hyper-realistic feed of the cameraman\'s future that dissolves nearby objects into geometric dust instantly' },
  { label: '33. วัตถุอาถรรพ์/ฟิสิกส์พัง 33', value: 'television set broadcasting a hyper-realistic feed of the cameraman\'s future that renders all nearby shadows in the wrong direction' },
  { label: '34. วัตถุอาถรรพ์/ฟิสิกส์พัง 34', value: 'child\'s toy robot that exhibits terrifyingly advanced AI movements that leaves a trail of frozen ice on any surface it touches' },
  { label: '35. วัตถุอาถรรพ์/ฟิสิกส์พัง 35', value: 'massive geometric obsidian monolith hovering silently that completely defies gravity within a 10-foot radius' },
  { label: '36. วัตถุอาถรรพ์/ฟิสิกส์พัง 36', value: 'vending machine deep in the woods filled with human bones that emits a low-frequency hum causing the camera sensor to vibrate' },
  { label: '37. วัตถุอาถรรพ์/ฟิสิกส์พัง 37', value: 'child\'s toy robot that exhibits terrifyingly advanced AI movements that flickers between existence and violent static every 2 seconds' },
  { label: '38. วัตถุอาถรรพ์/ฟิสิกส์พัง 38', value: 'rusted 1970s sedan that is organically breathing that emits a low-frequency hum causing the camera sensor to vibrate' },
  { label: '39. วัตถุอาถรรพ์/ฟิสิกส์พัง 39', value: 'television set broadcasting a hyper-realistic feed of the cameraman\'s future that emits a low-frequency hum causing the camera sensor to vibrate' },
  { label: '40. วัตถุอาถรรพ์/ฟิสิกส์พัง 40', value: 'television set broadcasting a hyper-realistic feed of the cameraman\'s future that leaves a trail of frozen ice on any surface it touches' },
  { label: '41. วัตถุอาถรรพ์/ฟิสิกส์พัง 41', value: 'child\'s toy robot that exhibits terrifyingly advanced AI movements that dissolves nearby objects into geometric dust instantly' },
  { label: '42. วัตถุอาถรรพ์/ฟิสิกส์พัง 42', value: 'refrigerator containing a pulsing fleshy core that screams with a human voice whenever light touches it' },
  { label: '43. วัตถุอาถรรพ์/ฟิสิกส์พัง 43', value: 'child\'s toy robot that exhibits terrifyingly advanced AI movements that renders all nearby shadows in the wrong direction' },
  { label: '44. วัตถุอาถรรพ์/ฟิสิกส์พัง 44', value: 'rusted 1970s sedan that is organically breathing that dissolves nearby objects into geometric dust instantly' },
  { label: '45. วัตถุอาถรรพ์/ฟิสิกส์พัง 45', value: 'television set broadcasting a hyper-realistic feed of the cameraman\'s future that screams with a human voice whenever light touches it' },
  { label: '46. วัตถุอาถรรพ์/ฟิสิกส์พัง 46', value: 'massive geometric obsidian monolith hovering silently that flickers between existence and violent static every 2 seconds' },
  { label: '47. วัตถุอาถรรพ์/ฟิสิกส์พัง 47', value: 'vending machine deep in the woods filled with human bones that screams with a human voice whenever light touches it' },
  { label: '48. วัตถุอาถรรพ์/ฟิสิกส์พัง 48', value: 'vending machine deep in the woods filled with human bones that flickers between existence and violent static every 2 seconds' },
  { label: '49. วัตถุอาถรรพ์/ฟิสิกส์พัง 49', value: 'television set broadcasting a hyper-realistic feed of the cameraman\'s future that completely defies gravity within a 10-foot radius' },
  { label: '50. วัตถุอาถรรพ์/ฟิสิกส์พัง 50', value: 'refrigerator containing a pulsing fleshy core that dissolves nearby objects into geometric dust instantly' },
  { label: '51. วัตถุอาถรรพ์/ฟิสิกส์พัง 51', value: 'vending machine deep in the woods filled with human bones that renders all nearby shadows in the wrong direction' },
  { label: '52. วัตถุอาถรรพ์/ฟิสิกส์พัง 52', value: 'vending machine deep in the woods filled with human bones that leaves a trail of frozen ice on any surface it touches' },
  { label: '53. วัตถุอาถรรพ์/ฟิสิกส์พัง 53', value: 'massive geometric obsidian monolith hovering silently that is slowly, organically consuming the concrete around it' },
  { label: '54. วัตถุอาถรรพ์/ฟิสิกส์พัง 54', value: 'door standing alone in an open field, leaking a blinding blue light that completely defies gravity within a 10-foot radius' },
  { label: '55. วัตถุอาถรรพ์/ฟิสิกส์พัง 55', value: 'perfectly spherical singularity consuming dust particles that is slowly, organically consuming the concrete around it' },
  { label: '56. วัตถุอาถรรพ์/ฟิสิกส์พัง 56', value: 'rusted 1970s sedan that is organically breathing that completely defies gravity within a 10-foot radius' },
  { label: '57. วัตถุอาถรรพ์/ฟิสิกส์พัง 57', value: 'massive geometric obsidian monolith hovering silently that screams with a human voice whenever light touches it' },
  { label: '58. วัตถุอาถรรพ์/ฟิสิกส์พัง 58', value: 'vending machine deep in the woods filled with human bones that dissolves nearby objects into geometric dust instantly' },
  { label: '59. วัตถุอาถรรพ์/ฟิสิกส์พัง 59', value: 'rusted 1970s sedan that is organically breathing that mirrors its environment with 100% physically accurate ray-tracing' },
  { label: '60. วัตถุอาถรรพ์/ฟิสิกส์พัง 60', value: 'child\'s toy robot that exhibits terrifyingly advanced AI movements that radiates intense waves of visual heat distortion' },
  { label: '61. วัตถุอาถรรพ์/ฟิสิกส์พัง 61', value: 'perfectly spherical singularity consuming dust particles that emits a low-frequency hum causing the camera sensor to vibrate' },
  { label: '62. วัตถุอาถรรพ์/ฟิสิกส์พัง 62', value: 'perfectly spherical singularity consuming dust particles that leaves a trail of frozen ice on any surface it touches' },
  { label: '63. วัตถุอาถรรพ์/ฟิสิกส์พัง 63', value: 'child\'s toy robot that exhibits terrifyingly advanced AI movements that emits a low-frequency hum causing the camera sensor to vibrate' },
  { label: '64. วัตถุอาถรรพ์/ฟิสิกส์พัง 64', value: 'refrigerator containing a pulsing fleshy core that leaves a trail of frozen ice on any surface it touches' },
  { label: '65. วัตถุอาถรรพ์/ฟิสิกส์พัง 65', value: 'massive geometric obsidian monolith hovering silently that emits a low-frequency hum causing the camera sensor to vibrate' },
  { label: '66. วัตถุอาถรรพ์/ฟิสิกส์พัง 66', value: 'massive geometric obsidian monolith hovering silently that renders all nearby shadows in the wrong direction' },
  { label: '67. วัตถุอาถรรพ์/ฟิสิกส์พัง 67', value: 'massive geometric obsidian monolith hovering silently that dissolves nearby objects into geometric dust instantly' },
  { label: '68. วัตถุอาถรรพ์/ฟิสิกส์พัง 68', value: 'refrigerator containing a pulsing fleshy core that flickers between existence and violent static every 2 seconds' },
  { label: '69. วัตถุอาถรรพ์/ฟิสิกส์พัง 69', value: 'massive geometric obsidian monolith hovering silently that mirrors its environment with 100% physically accurate ray-tracing' },
  { label: '70. วัตถุอาถรรพ์/ฟิสิกส์พัง 70', value: 'child\'s toy robot that exhibits terrifyingly advanced AI movements that screams with a human voice whenever light touches it' },
  { label: '71. วัตถุอาถรรพ์/ฟิสิกส์พัง 71', value: 'door standing alone in an open field, leaking a blinding blue light that mirrors its environment with 100% physically accurate ray-tracing' },
  { label: '72. วัตถุอาถรรพ์/ฟิสิกส์พัง 72', value: 'refrigerator containing a pulsing fleshy core that completely defies gravity within a 10-foot radius' },
  { label: '73. วัตถุอาถรรพ์/ฟิสิกส์พัง 73', value: 'vending machine deep in the woods filled with human bones that mirrors its environment with 100% physically accurate ray-tracing' },
  { label: '74. วัตถุอาถรรพ์/ฟิสิกส์พัง 74', value: 'child\'s toy robot that exhibits terrifyingly advanced AI movements that mirrors its environment with 100% physically accurate ray-tracing' },
  { label: '75. วัตถุอาถรรพ์/ฟิสิกส์พัง 75', value: 'massive geometric obsidian monolith hovering silently that leaves a trail of frozen ice on any surface it touches' },
  { label: '76. วัตถุอาถรรพ์/ฟิสิกส์พัง 76', value: 'door standing alone in an open field, leaking a blinding blue light that renders all nearby shadows in the wrong direction' },
  { label: '77. วัตถุอาถรรพ์/ฟิสิกส์พัง 77', value: 'perfectly spherical singularity consuming dust particles that renders all nearby shadows in the wrong direction' },
  { label: '78. วัตถุอาถรรพ์/ฟิสิกส์พัง 78', value: 'door standing alone in an open field, leaking a blinding blue light that screams with a human voice whenever light touches it' },
  { label: '79. วัตถุอาถรรพ์/ฟิสิกส์พัง 79', value: 'television set broadcasting a hyper-realistic feed of the cameraman\'s future that radiates intense waves of visual heat distortion' },
  { label: '80. วัตถุอาถรรพ์/ฟิสิกส์พัง 80', value: 'perfectly spherical singularity consuming dust particles that mirrors its environment with 100% physically accurate ray-tracing' },
  { label: '81. วัตถุอาถรรพ์/ฟิสิกส์พัง 81', value: 'refrigerator containing a pulsing fleshy core that is slowly, organically consuming the concrete around it' },
  { label: '82. วัตถุอาถรรพ์/ฟิสิกส์พัง 82', value: 'television set broadcasting a hyper-realistic feed of the cameraman\'s future that is slowly, organically consuming the concrete around it' },
  { label: '83. วัตถุอาถรรพ์/ฟิสิกส์พัง 83', value: 'child\'s toy robot that exhibits terrifyingly advanced AI movements that leaves a trail of frozen ice on any surface it touches' },
  { label: '84. วัตถุอาถรรพ์/ฟิสิกส์พัง 84', value: 'rusted 1970s sedan that is organically breathing that mirrors its environment with 100% physically accurate ray-tracing' },
  { label: '85. วัตถุอาถรรพ์/ฟิสิกส์พัง 85', value: 'door standing alone in an open field, leaking a blinding blue light that mirrors its environment with 100% physically accurate ray-tracing' },
  { label: '86. วัตถุอาถรรพ์/ฟิสิกส์พัง 86', value: 'perfectly spherical singularity consuming dust particles that flickers between existence and violent static every 2 seconds' },
  { label: '87. วัตถุอาถรรพ์/ฟิสิกส์พัง 87', value: 'vending machine deep in the woods filled with human bones that mirrors its environment with 100% physically accurate ray-tracing' },
  { label: '88. วัตถุอาถรรพ์/ฟิสิกส์พัง 88', value: 'perfectly spherical singularity consuming dust particles that is slowly, organically consuming the concrete around it' },
  { label: '89. วัตถุอาถรรพ์/ฟิสิกส์พัง 89', value: 'television set broadcasting a hyper-realistic feed of the cameraman\'s future that is slowly, organically consuming the concrete around it' },
  { label: '90. วัตถุอาถรรพ์/ฟิสิกส์พัง 90', value: 'television set broadcasting a hyper-realistic feed of the cameraman\'s future that emits a low-frequency hum causing the camera sensor to vibrate' },
  { label: '91. วัตถุอาถรรพ์/ฟิสิกส์พัง 91', value: 'perfectly spherical singularity consuming dust particles that leaves a trail of frozen ice on any surface it touches' },
  { label: '92. วัตถุอาถรรพ์/ฟิสิกส์พัง 92', value: 'child\'s toy robot that exhibits terrifyingly advanced AI movements that mirrors its environment with 100% physically accurate ray-tracing' },
  { label: '93. วัตถุอาถรรพ์/ฟิสิกส์พัง 93', value: 'perfectly spherical singularity consuming dust particles that renders all nearby shadows in the wrong direction' },
  { label: '94. วัตถุอาถรรพ์/ฟิสิกส์พัง 94', value: 'child\'s toy robot that exhibits terrifyingly advanced AI movements that dissolves nearby objects into geometric dust instantly' },
  { label: '95. วัตถุอาถรรพ์/ฟิสิกส์พัง 95', value: 'rusted 1970s sedan that is organically breathing that radiates intense waves of visual heat distortion' },
  { label: '96. วัตถุอาถรรพ์/ฟิสิกส์พัง 96', value: 'vending machine deep in the woods filled with human bones that renders all nearby shadows in the wrong direction' },
  { label: '97. วัตถุอาถรรพ์/ฟิสิกส์พัง 97', value: 'rusted 1970s sedan that is organically breathing that radiates intense waves of visual heat distortion' },
  { label: '98. วัตถุอาถรรพ์/ฟิสิกส์พัง 98', value: 'television set broadcasting a hyper-realistic feed of the cameraman\'s future that is slowly, organically consuming the concrete around it' },
  { label: '99. วัตถุอาถรรพ์/ฟิสิกส์พัง 99', value: 'television set broadcasting a hyper-realistic feed of the cameraman\'s future that renders all nearby shadows in the wrong direction' },
  { label: '100. วัตถุอาถรรพ์/ฟิสิกส์พัง 100', value: 'massive geometric obsidian monolith hovering silently that radiates intense waves of visual heat distortion' },
  { label: 'ระบุเอง (Custom)', value: 'custom' }
];

