// Auto-generated continuity configurations

export const PROTAGONISTS: string[] = [
  "a tired delivery driver wearing clinical scrubs",
  "a paramedic off-duty with muddy boots and a flannel shirt",
  "a rugged outdoorsman in bright athletic running gear",
  "a security guard wearing a torn denim jacket",
  "a curious female urban explorer with muddy boots and a flannel shirt",
  "a scruffy 30-year-old guy with muddy boots and a flannel shirt",
  "a rugged outdoorsman wearing a neat security uniform",
  "a 25-year-old Asian man in a stained mechanic's jumpsuit",
  "a paramedic off-duty in professional office attire",
  "a middle-aged Caucasian male wearing a heavy winter trench coat",
  "a tired delivery driver in a stained mechanic's jumpsuit",
  "a exhausted teenager with a thick beard and heavy backpack",
  "a anxious young mother wearing a yellow waterproof rain jacket",
  "a tired delivery driver wearing a heavy winter trench coat",
  "a rugged outdoorsman wearing a heavy winter trench coat",
  "a exhausted teenager wearing clinical scrubs",
  "a college student with a thick beard and heavy backpack",
  "a tired delivery driver wearing a torn denim jacket",
  "a 25-year-old Asian man wearing a torn denim jacket",
  "a elderly Hispanic man in camouflage cargo pants",
  "a security guard with muddy boots and a flannel shirt",
  "a elderly Hispanic man wearing a heavy winter trench coat",
  "a scruffy 30-year-old guy in professional office attire",
  "a college student wearing clinical scrubs",
  "a exhausted teenager in camouflage cargo pants",
  "a athletic young woman in camouflage cargo pants",
  "a terrified young African-American woman with muddy boots and a flannel shirt",
  "a exhausted teenager wearing a neat security uniform",
  "a anxious young mother wearing a torn denim jacket",
  "a college student with muddy boots and a flannel shirt",
  "a middle-aged Caucasian male in a stained mechanic's jumpsuit",
  "a athletic young woman with muddy boots and a flannel shirt",
  "a elderly Hispanic man in bright athletic running gear",
  "a scruffy 30-year-old guy in camouflage cargo pants",
  "a paramedic off-duty in camouflage cargo pants",
  "a 25-year-old Asian man wearing a heavy winter trench coat",
  "a tired delivery driver with a thick beard and heavy backpack",
  "a middle-aged Caucasian male in camouflage cargo pants",
  "a middle-aged Caucasian male in bright athletic running gear",
  "a 25-year-old Asian man with a thick beard and heavy backpack",
  "a 25-year-old Asian man wearing a neat security uniform",
  "a security guard wearing a faded vintage oversized t-shirt",
  "a 25-year-old Asian man in bright athletic running gear",
  "a curious female urban explorer in a stained mechanic's jumpsuit",
  "a college student wearing a faded vintage oversized t-shirt",
  "a elderly Hispanic man with a thick beard and heavy backpack",
  "a athletic young woman in professional office attire",
  "a exhausted teenager with muddy boots and a flannel shirt",
  "a exhausted teenager in bright athletic running gear",
  "a athletic young woman in bright athletic running gear",
  "a rugged outdoorsman in a stained mechanic's jumpsuit",
  "a rugged outdoorsman wearing a yellow waterproof rain jacket",
  "a paramedic off-duty in a stained mechanic's jumpsuit",
  "a terrified young African-American woman wearing clinical scrubs",
  "a anxious young mother in a stained mechanic's jumpsuit",
  "a middle-aged Caucasian male in professional office attire",
  "a curious female urban explorer in professional office attire",
  "a rugged outdoorsman wearing a faded vintage oversized t-shirt",
  "a paramedic off-duty with a thick beard and heavy backpack",
  "a curious female urban explorer wearing a yellow waterproof rain jacket",
  "a anxious young mother in professional office attire",
  "a terrified young African-American woman wearing a torn denim jacket",
  "a security guard in a stained mechanic's jumpsuit",
  "a college student in professional office attire",
  "a rugged outdoorsman with a thick beard and heavy backpack",
  "a security guard wearing clinical scrubs",
  "a 25-year-old Asian man in camouflage cargo pants",
  "a scruffy 30-year-old guy wearing a heavy winter trench coat",
  "a athletic young woman with a thick beard and heavy backpack",
  "a rugged outdoorsman in professional office attire",
  "a scruffy 30-year-old guy in bright athletic running gear",
  "a terrified young African-American woman wearing a neat security uniform",
  "a anxious young mother wearing clinical scrubs",
  "a athletic young woman wearing a yellow waterproof rain jacket",
  "a elderly Hispanic man in a stained mechanic's jumpsuit",
  "a tired delivery driver in camouflage cargo pants",
  "a anxious young mother in bright athletic running gear",
  "a 25-year-old Asian man wearing a yellow waterproof rain jacket",
  "a elderly Hispanic man wearing a torn denim jacket",
  "a paramedic off-duty wearing a faded vintage oversized t-shirt",
  "a middle-aged Caucasian male wearing a yellow waterproof rain jacket",
  "a scruffy 30-year-old guy wearing a faded vintage oversized t-shirt",
  "a college student wearing a yellow waterproof rain jacket",
  "a security guard in bright athletic running gear",
  "a tired delivery driver with muddy boots and a flannel shirt",
  "a college student wearing a heavy winter trench coat",
  "a elderly Hispanic man wearing a yellow waterproof rain jacket",
  "a college student in bright athletic running gear",
  "a rugged outdoorsman wearing a torn denim jacket",
  "a scruffy 30-year-old guy with a thick beard and heavy backpack",
  "a curious female urban explorer wearing a faded vintage oversized t-shirt",
  "a curious female urban explorer in camouflage cargo pants",
  "a exhausted teenager in professional office attire",
  "a rugged outdoorsman with muddy boots and a flannel shirt",
  "a terrified young African-American woman in professional office attire",
  "a tired delivery driver wearing a yellow waterproof rain jacket",
  "a elderly Hispanic man wearing clinical scrubs",
  "a tired delivery driver wearing a faded vintage oversized t-shirt",
  "a paramedic off-duty wearing a neat security uniform",
  "a anxious young mother wearing a neat security uniform",
  "a terrified young African-American woman in bright athletic running gear",
  "a security guard in camouflage cargo pants",
  "a elderly Hispanic man wearing a neat security uniform",
  "a exhausted teenager wearing a yellow waterproof rain jacket",
  "a tired delivery driver in bright athletic running gear",
  "a exhausted teenager in a stained mechanic's jumpsuit",
  "a curious female urban explorer wearing clinical scrubs",
  "a tired delivery driver wearing a neat security uniform",
  "a security guard wearing a neat security uniform",
  "a security guard wearing a yellow waterproof rain jacket",
  "a scruffy 30-year-old guy in a stained mechanic's jumpsuit",
  "a elderly Hispanic man in professional office attire",
  "a middle-aged Caucasian male with a thick beard and heavy backpack",
  "a terrified young African-American woman wearing a faded vintage oversized t-shirt",
  "a scruffy 30-year-old guy wearing clinical scrubs",
  "a athletic young woman wearing a heavy winter trench coat",
  "a athletic young woman wearing clinical scrubs",
  "a terrified young African-American woman in camouflage cargo pants",
  "a curious female urban explorer wearing a torn denim jacket",
  "a exhausted teenager wearing a faded vintage oversized t-shirt",
  "a paramedic off-duty wearing a yellow waterproof rain jacket",
  "a terrified young African-American woman wearing a heavy winter trench coat",
  "a anxious young mother wearing a faded vintage oversized t-shirt",
  "a terrified young African-American woman wearing a yellow waterproof rain jacket",
  "a exhausted teenager wearing a torn denim jacket",
  "a scruffy 30-year-old guy wearing a yellow waterproof rain jacket",
  "a terrified young African-American woman with a thick beard and heavy backpack",
  "a middle-aged Caucasian male wearing a faded vintage oversized t-shirt",
  "a college student wearing a torn denim jacket",
  "a 25-year-old Asian man with muddy boots and a flannel shirt",
  "a anxious young mother with muddy boots and a flannel shirt",
  "a curious female urban explorer in bright athletic running gear",
  "a athletic young woman in a stained mechanic's jumpsuit",
  "a middle-aged Caucasian male with muddy boots and a flannel shirt",
  "a elderly Hispanic man wearing a faded vintage oversized t-shirt",
  "a middle-aged Caucasian male wearing clinical scrubs",
  "a athletic young woman wearing a torn denim jacket",
  "a anxious young mother wearing a heavy winter trench coat",
  "a middle-aged Caucasian male wearing a neat security uniform",
  "a terrified young African-American woman in a stained mechanic's jumpsuit",
  "a rugged outdoorsman in camouflage cargo pants",
  "a tired delivery driver in professional office attire",
  "a paramedic off-duty wearing a torn denim jacket",
  "a paramedic off-duty wearing clinical scrubs",
  "a curious female urban explorer wearing a heavy winter trench coat",
  "a anxious young mother in camouflage cargo pants",
  "a exhausted teenager wearing a heavy winter trench coat",
  "a security guard in professional office attire",
  "a 25-year-old Asian man wearing clinical scrubs",
  "a security guard wearing a heavy winter trench coat",
  "a paramedic off-duty wearing a heavy winter trench coat",
  "a rugged outdoorsman wearing clinical scrubs",
  "a elderly Hispanic man with muddy boots and a flannel shirt",
  "a anxious young mother with a thick beard and heavy backpack",
  "a college student in camouflage cargo pants",
  "a 25-year-old Asian man wearing a faded vintage oversized t-shirt",
  "a athletic young woman wearing a neat security uniform",
  "a scruffy 30-year-old guy wearing a neat security uniform",
  "a 25-year-old Asian man in professional office attire",
  "a curious female urban explorer wearing a neat security uniform",
  "a curious female urban explorer with a thick beard and heavy backpack",
  "a college student in a stained mechanic's jumpsuit",
  "a scruffy 30-year-old guy wearing a torn denim jacket",
  "a paramedic off-duty in bright athletic running gear",
  "a college student wearing a neat security uniform",
  "a security guard with a thick beard and heavy backpack",
  "a middle-aged Caucasian male wearing a torn denim jacket",
  "a athletic young woman wearing a faded vintage oversized t-shirt",
];

export const MACGUFFIN_PROPS: string[] = [
  "a ceramic vase wrapped tightly in thick, unnaturally cold iron chains",
  "a stone obelisk fragment covered in a thick layer of biological slime",
  "a metallic canister wrapped tightly in thick, unnaturally cold iron chains",
  "a cryogenic pod leaking a foul-smelling green gas",
  "a titanium briefcase that appears to be slowly breathing",
  "a cryogenic pod wrapped tightly in thick, unnaturally cold iron chains",
  "a ceramic vase emitting a soft, hypnotic low-frequency hum",
  "a wooden box covered in deep aggressive claw marks",
  "a metallic canister pulsating with a soft inner light",
  "a glass terrarium wrapped tightly in thick, unnaturally cold iron chains",
  "a steel container covered in glowing microscopic runes",
  "a stone obelisk fragment leaking a foul-smelling green gas",
  "a leather-bound chest covered in a thick layer of biological slime",
  "a stone obelisk fragment that defies gravity by hovering slightly off the ground",
  "a glass terrarium leaking a foul-smelling green gas",
  "a cryogenic pod pulsating with a soft inner light",
  "a wooden box emitting a soft, hypnotic low-frequency hum",
  "a titanium briefcase covered in deep aggressive claw marks",
  "a titanium briefcase covered in glowing microscopic runes",
  "a leather-bound chest that appears to be slowly breathing",
  "a ceramic vase covered in glowing microscopic runes",
  "a glass terrarium that appears to be slowly breathing",
  "a stone obelisk fragment emitting a soft, hypnotic low-frequency hum",
  "a stone obelisk fragment that appears to be slowly breathing",
  "a ceramic vase pulsating with a soft inner light",
  "a glass terrarium covered in deep aggressive claw marks",
  "a titanium briefcase pulsating with a soft inner light",
  "a metallic canister covered in glowing microscopic runes",
  "a steel container wrapped tightly in thick, unnaturally cold iron chains",
  "a leather-bound chest wrapped tightly in thick, unnaturally cold iron chains",
  "a steel container covered in deep aggressive claw marks",
  "a metallic canister leaking a foul-smelling green gas",
  "a steel container that defies gravity by hovering slightly off the ground",
  "a cryogenic pod that appears to be slowly breathing",
  "a cryogenic pod that defies gravity by hovering slightly off the ground",
  "a leather-bound chest leaking a foul-smelling green gas",
  "a cryogenic pod covered in glowing microscopic runes",
  "a steel container pulsating with a soft inner light",
  "a ceramic vase that appears to be slowly breathing",
  "a metallic canister covered in deep aggressive claw marks",
  "a metallic canister that defies gravity by hovering slightly off the ground",
  "a glass terrarium pulsating with a soft inner light",
  "a wooden box covered in glowing microscopic runes",
  "a cryogenic pod covered in a thick layer of biological slime",
  "a titanium briefcase leaking a foul-smelling green gas",
  "a titanium briefcase emitting a soft, hypnotic low-frequency hum",
  "a steel container that appears to be slowly breathing",
  "a obsidian geometric sphere that appears to be slowly breathing",
  "a obsidian geometric sphere wrapped tightly in thick, unnaturally cold iron chains",
  "a wooden box wrapped tightly in thick, unnaturally cold iron chains",
  "a cryogenic pod covered in deep aggressive claw marks",
  "a leather-bound chest pulsating with a soft inner light",
  "a steel container leaking a foul-smelling green gas",
  "a ceramic vase covered in deep aggressive claw marks",
  "a ceramic vase covered in a thick layer of biological slime",
  "a ceramic vase that defies gravity by hovering slightly off the ground",
  "a metallic canister covered in a thick layer of biological slime",
  "a obsidian geometric sphere pulsating with a soft inner light",
  "a steel container emitting a soft, hypnotic low-frequency hum",
  "a wooden box that appears to be slowly breathing",
  "a obsidian geometric sphere covered in glowing microscopic runes",
  "a obsidian geometric sphere leaking a foul-smelling green gas",
  "a steel container covered in a thick layer of biological slime",
  "a leather-bound chest emitting a soft, hypnotic low-frequency hum",
  "a wooden box pulsating with a soft inner light",
  "a wooden box leaking a foul-smelling green gas",
  "a glass terrarium covered in glowing microscopic runes",
  "a ceramic vase leaking a foul-smelling green gas",
  "a glass terrarium covered in a thick layer of biological slime",
  "a titanium briefcase that defies gravity by hovering slightly off the ground",
  "a leather-bound chest covered in deep aggressive claw marks",
  "a stone obelisk fragment covered in glowing microscopic runes",
  "a obsidian geometric sphere that defies gravity by hovering slightly off the ground",
  "a obsidian geometric sphere covered in a thick layer of biological slime",
  "a titanium briefcase wrapped tightly in thick, unnaturally cold iron chains",
  "a cryogenic pod emitting a soft, hypnotic low-frequency hum",
  "a titanium briefcase covered in a thick layer of biological slime",
  "a wooden box that defies gravity by hovering slightly off the ground",
  "a obsidian geometric sphere emitting a soft, hypnotic low-frequency hum",
  "a glass terrarium that defies gravity by hovering slightly off the ground",
  "a glass terrarium emitting a soft, hypnotic low-frequency hum",
  "a stone obelisk fragment covered in deep aggressive claw marks",
  "a leather-bound chest covered in glowing microscopic runes",
  "a stone obelisk fragment pulsating with a soft inner light",
  "a metallic canister emitting a soft, hypnotic low-frequency hum",
  "a leather-bound chest that defies gravity by hovering slightly off the ground",
  "a stone obelisk fragment wrapped tightly in thick, unnaturally cold iron chains",
  "a metallic canister that appears to be slowly breathing",
  "a obsidian geometric sphere covered in deep aggressive claw marks",
  "a wooden box covered in a thick layer of biological slime",
];
