export const DIALOGUES: string[] = [
  "What the hell is that?",
  "Oh my goodness.",
  "Look out!",
  "Get down!",
  "Back away slowly.",
  "Unbelievable.",
  "This can't be real.",
  "Am I hallucinating?",
  "Holy crap.",
  "Wow.",
  "Please tell me you got that on camera.",
  "That was too close.",
  "I'm speechless.",
  "Look at that! this shouldn't exist. This is history.",
  "Look at that! it's glowing. I need to get closer.",
  "Hey guys, it's coming closer. Just keep recording.",
  "No way. I can't tear my eyes away. I hope it's friendly.",
  "This changes everything. is it dangerous? Let me try to touch it.",
  "Stay back. did it just make a sound? This is history.",
  "Seriously? did it just make a sound? This is history.",
  "This changes everything. it looks like it's from another planet. I'm terrified.",
  "Is this real? it's staring right at me. Let's get out of here.",
  "Seriously? it's absolutely massive. It's so beautiful.",
  "Are you seeing this? it's glowing. Run!",
  "I'm shaking right now. this is going to go viral. I'm getting goosebumps.",
  "What on earth... this shouldn't exist. It's so beautiful.",
  "Seriously? how is this even possible? Run!",
  "I've never seen anything like it. I have a really bad feeling about this. Run!",
  "Oh my god, is it dangerous? Let's call for help.",
  "You won't believe what I just found. do you think it sees us? What do we do?",
  "You won't believe what I just found. it's staring right at me. It's so beautiful.",
  "This changes everything. this is the craziest thing ever. I hope it's friendly.",
  "Are you seeing this? how is this even possible? Let's get out of here.",
  "Are you seeing this? is it dangerous? We have to show someone.",
  "Are you seeing this? did it just make a sound? We have to show someone.",
  "You won't believe what I just found. this shouldn't exist. Let me try to touch it.",
  "Quick, record this. this shouldn't exist. This is history.",
  "Oh my god, I think it's moving. Don't make a sound.",
  "Oh my god, we need to leave right now. Just keep recording.",
  "Hey guys, do you think it sees us? This is history.",
  "Is this real? this is breathtaking. Just keep recording.",
  "Oh my god, this is going to go viral. Don't make a sound.",
  "No way. this is breathtaking. Don't make a sound.",
  "This is insane. I have a really bad feeling about this. Just keep recording.",
  "I can't believe this, I'm not sure what to do. What do we do?",
  "Wait, hold on. did it just make a sound? It's so beautiful.",
  "Stay back. how is this even possible? Let's get out of here.",
  "Hey guys, this is the craziest thing ever. This is history.",
  "I'm shaking right now. I'm not sure what to do. It's so beautiful.",
  "Seriously? I think it's moving. I hope it's friendly.",
  "No way. this is breathtaking. It's so beautiful.",
  "Oh my god, I can't tear my eyes away. It's so beautiful.",
  "You won't believe what I just found. is it dangerous? I'm terrified.",
  "Wait, hold on. it's coming closer. Don't make a sound.",
  "You won't believe what I just found. this shouldn't exist. Run!",
  "I've never seen anything like it. this shouldn't exist. Let me try to touch it.",
  "Is this real? I can't tear my eyes away. We have to show someone.",
  "What on earth... how is this even possible? I'm getting goosebumps.",
  "Wait, hold on. I'm not sure what to do. Just keep recording.",
  "Oh my god, how is this even possible? This is history.",
  "No way. this shouldn't exist. Just keep recording.",
  "Are you seeing this? I think it's moving. It's so beautiful.",
  "Look at that! is it dangerous? I'm terrified.",
  "What on earth... this is going to go viral. Let me try to touch it.",
  "Quick, record this. is it dangerous? Just keep recording.",
  "I can't believe this, did it just make a sound? It's so beautiful.",
  "This changes everything. it's coming closer. Just keep recording.",
  "Wait, hold on. I'm not sure what to do. Let's call for help.",
  "Are you seeing this? it's coming closer. I hope it's friendly.",
  "Wait, hold on. it's absolutely massive. I'm terrified.",
  "You won't believe what I just found. it's coming closer. Just keep recording.",
  "You won't believe what I just found. is it dangerous? Don't make a sound.",
  "No way. it looks like it's from another planet. This is history.",
  "Hey guys, it looks like it's from another planet. Run!",
  "I've never seen anything like it. this is going to go viral. Let's get out of here.",
  "I can't believe this, this is going to go viral. Let's call for help.",
  "Is this real? I think it's moving. I need to get closer.",
  "I can't believe this, it's staring right at me. I'm terrified.",
  "What on earth... I think it's moving. I'm terrified.",
  "I've never seen anything like it. it's absolutely massive. Don't make a sound.",
  "This changes everything. it looks like it's from another planet. Let's call for help.",
  "I'm shaking right now. is it dangerous? What do we do?",
  "Seriously? I'm not sure what to do. Let me try to touch it.",
  "Quick, record this. it's coming closer. I hope it's friendly.",
  "Are you seeing this? I think it's moving. Don't make a sound.",
  "Is this real? I have a really bad feeling about this. I'm getting goosebumps.",
  "I've never seen anything like it. this is going to go viral. Don't make a sound.",
  "Is this real? I have a really bad feeling about this. What do we do?",
  "Is this real? we need to leave right now. I'm terrified.",
  "Stay back. it's absolutely massive. Don't make a sound.",
  "Hey guys, how is this even possible? Let's call for help.",
  "I can't believe this, it's glowing. I'm terrified.",
  "This changes everything. we need to leave right now. Let's call for help.",
  "No way. this is going to go viral. Let's call for help.",
  "What on earth... I have a really bad feeling about this. It's so beautiful.",
  "This changes everything. did it just make a sound? It's so beautiful.",
  "You won't believe what I just found. it's glowing. Don't make a sound.",
  "I can't believe this, it's staring right at me. Let's get out of here.",
  "This is insane. I can't tear my eyes away. Just keep recording.",
  "You won't believe what I just found. this is the craziest thing ever. Let's call for help.",
  "This changes everything. this is the craziest thing ever. Don't make a sound.",
  "I'm shaking right now. it's absolutely massive. I need to get closer.",
  "Seriously? it looks like it's from another planet. Run!",
  "I'm shaking right now. I have a really bad feeling about this. Don't make a sound.",
  "I'm shaking right now. this is the craziest thing ever. I hope it's friendly.",
  "This is insane. how is this even possible? Don't make a sound.",
  "I'm shaking right now. it's glowing. Just keep recording.",
  "Hey guys, do you think it sees us? It's so beautiful.",
  "No way. this is the craziest thing ever. I hope it's friendly.",
  "Hey guys, it's coming closer. We have to show someone.",
  "No way. it's absolutely massive. Let's call for help.",
  "Oh my god, it looks like it's from another planet. I need to get closer.",
  "I've never seen anything like it. I think it's moving. Don't make a sound.",
  "Stay back. this is breathtaking. This is history.",
  "Look at that! it's staring right at me. I'm getting goosebumps.",
  "I've never seen anything like it. is it dangerous? This is history.",
  "I'm shaking right now. it's absolutely massive. Let's call for help.",
  "Oh my god, do you think it sees us? I need to get closer.",
  "Seriously? I have a really bad feeling about this. I need to get closer.",
  "Is this real? it's absolutely massive. I'm terrified.",
  "I'm shaking right now. this shouldn't exist. I'm getting goosebumps.",
  "Are you seeing this? I think it's moving. We have to show someone.",
  "Wait, hold on. this is breathtaking. Let's call for help.",
  "Oh my god, it's staring right at me. I hope it's friendly.",
  "What on earth... it looks like it's from another planet. I'm terrified.",
  "I'm shaking right now. I'm not sure what to do. I need to get closer.",
  "Are you seeing this? did it just make a sound? It's so beautiful.",
  "What on earth... I think it's moving. I hope it's friendly.",
  "You won't believe what I just found. it's absolutely massive. I hope it's friendly.",
  "Oh my god, this is the craziest thing ever. I need to get closer.",
  "You won't believe what I just found. I think it's moving. What do we do?",
  "Stay back. did it just make a sound? Run!",
  "Seriously? I can't tear my eyes away. I'm getting goosebumps.",
  "What on earth... we need to leave right now. It's so beautiful.",
  "Oh my god, I think it's moving. I'm getting goosebumps.",
  "No way. we need to leave right now. I'm getting goosebumps.",
  "Are you seeing this? it looks like it's from another planet. This is history.",
  "I can't believe this, I have a really bad feeling about this. I'm terrified.",
  "I can't believe this, we need to leave right now. Just keep recording.",
  "I'm shaking right now. it's coming closer. I'm getting goosebumps.",
  "Stay back. it's staring right at me. This is history.",
  "Quick, record this. this is breathtaking. Let's get out of here.",
  "Hey guys, did it just make a sound? It's so beautiful.",
  "Stay back. it's glowing. Just keep recording.",
  "What on earth... it's glowing. I'm terrified.",
  "I'm shaking right now. this is the craziest thing ever. Let's get out of here.",
  "I've never seen anything like it. I think it's moving. This is history.",
  "What on earth... how is this even possible? Let's call for help.",
  "Oh my god, it's staring right at me. It's so beautiful.",
  "What on earth... I think it's moving. We have to show someone.",
  "Seriously? it's absolutely massive. What do we do?",
  "Is this real? this is breathtaking. I need to get closer.",
  "Wait, hold on. it's glowing. Just keep recording.",
  "No way. it's coming closer. Let's call for help.",
  "Seriously? it's glowing. Let's get out of here.",
  "Oh my god, it's coming closer. Let's call for help.",
  "Look at that! is it dangerous? Run!",
  "Quick, record this. we need to leave right now. This is history.",
  "You won't believe what I just found. it looks like it's from another planet. We have to show someone.",
  "I can't believe this, this is breathtaking. Don't make a sound.",
  "Seriously? this is the craziest thing ever. I need to get closer.",
  "Wait, hold on. I can't tear my eyes away. I hope it's friendly.",
  "This changes everything. it's glowing. I need to get closer.",
  "Hey guys, I can't tear my eyes away. Run!",
  "This is insane. it's coming closer. I'm terrified.",
  "Wait, hold on. it's absolutely massive. What do we do?",
  "Hey guys, I think it's moving. Don't make a sound.",
  "Is this real? it looks like it's from another planet. It's so beautiful.",
  "What on earth... it's staring right at me. Just keep recording.",
  "Quick, record this. is it dangerous? I'm terrified.",
  "Wait, hold on. did it just make a sound? Don't make a sound.",
  "Seriously? I'm not sure what to do. Don't make a sound.",
  "What on earth... how is this even possible? Let me try to touch it.",
  "Look at that! it's glowing. We have to show someone.",
  "This changes everything. it looks like it's from another planet. This is history.",
  "I've never seen anything like it. this is the craziest thing ever. It's so beautiful.",
  "Wait, hold on. it's glowing. Run!",
  "This is insane. I have a really bad feeling about this. I'm getting goosebumps.",
  "You won't believe what I just found. is it dangerous? I need to get closer.",
  "What on earth... do you think it sees us? Don't make a sound.",
  "Seriously? do you think it sees us? I'm terrified.",
  "Hey guys, I think it's moving. Let me try to touch it.",
  "Quick, record this. do you think it sees us? Run!",
  "Quick, record this. we need to leave right now. What do we do?",
  "Look at that! do you think it sees us? I'm terrified.",
  "Seriously? I'm not sure what to do. I need to get closer.",
  "What on earth... it's staring right at me. Run!",
  "Oh my god, is it dangerous? Run!",
  "I'm shaking right now. I think it's moving. Let's call for help.",
  "Is this real? I think it's moving. I'm terrified.",
  "No way. I have a really bad feeling about this. Run!",
  "Hey guys, I have a really bad feeling about this. Just keep recording.",
  "Quick, record this. it's glowing. Let's call for help.",
  "Quick, record this. it looks like it's from another planet. I need to get closer.",
  "Stay back. how is this even possible? I'm getting goosebumps.",
  "Are you seeing this? do you think it sees us? I'm terrified.",
  "Seriously? this shouldn't exist. I'm terrified.",
  "This changes everything. I can't tear my eyes away. This is history.",
  "Quick, record this. did it just make a sound? I hope it's friendly.",
  "Quick, record this. it's absolutely massive. I hope it's friendly.",
  "No way. this is breathtaking. What do we do?",
  "Oh my god, it's coming closer. I'm terrified.",
  "Hey guys, it's absolutely massive. This is history.",
  "What on earth... it's absolutely massive. This is history.",
  "Hey guys, this shouldn't exist. Let's call for help.",
  "Seriously? it looks like it's from another planet. I hope it's friendly.",
  "I can't believe this, how is this even possible? Run!",
  "No way. it's coming closer. What do we do?",
  "Are you seeing this? it looks like it's from another planet. What do we do?",
  "Is this real? we need to leave right now. Just keep recording.",
  "No way. how is this even possible? This is history.",
  "Stay back. did it just make a sound? I need to get closer.",
  "I've never seen anything like it. I have a really bad feeling about this. Let's get out of here.",
  "I'm shaking right now. this is going to go viral. I hope it's friendly.",
  "Quick, record this. it's coming closer. I'm terrified.",
  "This changes everything. I'm not sure what to do. I'm getting goosebumps.",
  "Are you seeing this? it's coming closer. I need to get closer.",
  "What on earth... this is the craziest thing ever. Let's call for help.",
  "This changes everything. it's coming closer. I'm getting goosebumps.",
  "You won't believe what I just found. it's staring right at me. Just keep recording.",
  "Oh my god, do you think it sees us? I hope it's friendly.",
  "What on earth... I'm not sure what to do. What do we do?",
  "I've never seen anything like it. we need to leave right now. I'm terrified.",
  "Are you seeing this? this is the craziest thing ever. I'm terrified.",
  "What on earth... it's staring right at me. This is history.",
  "Are you seeing this? I have a really bad feeling about this. Run!",
  "Wait, hold on. it's absolutely massive. I'm getting goosebumps.",
  "I'm shaking right now. I'm not sure what to do. We have to show someone.",
  "Quick, record this. it's staring right at me. It's so beautiful.",
  "Hey guys, it's absolutely massive. Let me try to touch it.",
  "I've never seen anything like it. did it just make a sound? What do we do?",
  "Look at that! this is breathtaking. I'm terrified.",
  "Look at that! it's absolutely massive. Let me try to touch it.",
  "Hey guys, we need to leave right now. I need to get closer.",
  "Is this real? do you think it sees us? Don't make a sound.",
  "Oh my god, I think it's moving. I'm terrified.",
  "Are you seeing this? do you think it sees us? Let me try to touch it.",
  "I've never seen anything like it. it's absolutely massive. Let's call for help.",
  "I've never seen anything like it. I can't tear my eyes away. I'm terrified.",
  "Quick, record this. it looks like it's from another planet. Don't make a sound.",
  "Stay back. do you think it sees us? I'm terrified.",
  "No way. it's coming closer. I hope it's friendly.",
  "Oh my god, how is this even possible? I need to get closer.",
  "I can't believe this, I have a really bad feeling about this. Run!",
  "No way. this is the craziest thing ever. Let's call for help.",
  "This changes everything. I think it's moving. It's so beautiful.",
  "Seriously? this is going to go viral. Run!",
  "Are you seeing this? did it just make a sound? What do we do?",
  "This is insane. I'm not sure what to do. I'm getting goosebumps.",
  "Are you seeing this? it's absolutely massive. Just keep recording.",
  "You won't believe what I just found. do you think it sees us? Let me try to touch it.",
  "You won't believe what I just found. this is breathtaking. I'm getting goosebumps.",
  "This changes everything. did it just make a sound? Let me try to touch it.",
  "What on earth... I can't tear my eyes away. I'm getting goosebumps.",
  "Is this real? this is the craziest thing ever. Just keep recording.",
  "I'm shaking right now. I think it's moving. What do we do?",
  "I'm shaking right now. I can't tear my eyes away. I hope it's friendly.",
  "Are you seeing this? this is going to go viral. I need to get closer.",
  "I've never seen anything like it. I think it's moving. Let's get out of here.",
  "Is this real? it's coming closer. Let me try to touch it.",
  "Are you seeing this? it's coming closer. Just keep recording.",
  "Quick, record this. it's staring right at me. This is history.",
  "Seriously? it's coming closer. Run!",
  "Stay back. this is going to go viral. Run!",
  "This changes everything. it's absolutely massive. I need to get closer.",
  "Stay back. I'm not sure what to do. Let's call for help.",
  "Quick, record this. this is going to go viral. We have to show someone.",
  "Look at that! it's absolutely massive. Run!",
  "Are you seeing this? I think it's moving. I hope it's friendly.",
  "Seriously? did it just make a sound? I'm terrified.",
  "Wait, hold on. I think it's moving. I need to get closer.",
  "This changes everything. do you think it sees us? We have to show someone.",
  "This is insane. how is this even possible? Let's call for help.",
  "I'm shaking right now. do you think it sees us? Let's call for help.",
  "No way. this is the craziest thing ever. Just keep recording.",
  "Wait, hold on. do you think it sees us? I'm getting goosebumps.",
  "No way. this is breathtaking. I need to get closer.",
  "I can't believe this, I can't tear my eyes away. We have to show someone.",
  "No way. this shouldn't exist. Let's call for help.",
  "Quick, record this. this shouldn't exist. We have to show someone.",
  "Seriously? it's staring right at me. I hope it's friendly.",
  "Look at that! this shouldn't exist. I need to get closer.",
  "Is this real? it's glowing. Run!",
  "Are you seeing this? we need to leave right now. I'm terrified.",
  "Wait, hold on. this is the craziest thing ever. I need to get closer.",
  "No way. I think it's moving. I'm terrified.",
  "Quick, record this. this shouldn't exist. Let's call for help.",
  "Seriously? we need to leave right now. Don't make a sound.",
  "Are you seeing this? I'm not sure what to do. Let me try to touch it.",
  "What on earth... it's glowing. Let's get out of here.",
  "No way. it's glowing. Let's get out of here.",
  "What on earth... we need to leave right now. I'm terrified.",
  "You won't believe what I just found. I think it's moving. This is history.",
  "I can't believe this, I have a really bad feeling about this. Let's get out of here.",
  "Look at that! it's staring right at me. We have to show someone.",
  "No way. I have a really bad feeling about this. I need to get closer.",
  "I've never seen anything like it. is it dangerous? Let's call for help.",
  "This is insane. we need to leave right now. It's so beautiful.",
  "Oh my god, how is this even possible? What do we do?",
  "Look at that! this shouldn't exist. Don't make a sound.",
  "Quick, record this. this is going to go viral. Run!",
  "I'm shaking right now. I can't tear my eyes away. We have to show someone.",
  "What on earth... do you think it sees us? Just keep recording.",
  "Look at that! do you think it sees us? Don't make a sound.",
  "I can't believe this, it looks like it's from another planet. Just keep recording.",
  "Stay back. is it dangerous? Don't make a sound.",
  "Wait, hold on. it's coming closer. Let me try to touch it.",
  "I can't believe this, I'm not sure what to do. Let me try to touch it.",
  "Seriously? we need to leave right now. Let's call for help.",
  "I can't believe this, it's coming closer. Let's get out of here.",
  "Hey guys, this is the craziest thing ever. It's so beautiful.",
  "Wait, hold on. it's glowing. I need to get closer.",
  "This is insane. this is the craziest thing ever. Don't make a sound.",
  "What on earth... do you think it sees us? We have to show someone.",
  "What on earth... I have a really bad feeling about this. Let's call for help.",
  "What on earth... it's glowing. Run!",
  "Hey guys, this is going to go viral. I'm terrified.",
  "Stay back. did it just make a sound? Don't make a sound.",
  "Oh my god, it looks like it's from another planet. Run!",
  "I'm shaking right now. it's staring right at me. I'm terrified.",
  "Are you seeing this? do you think it sees us? Let's call for help.",
  "Seriously? this is going to go viral. I need to get closer.",
  "Hey guys, do you think it sees us? We have to show someone.",
  "What on earth... it's coming closer. I need to get closer.",
  "I've never seen anything like it. it's coming closer. Let me try to touch it.",
  "Seriously? we need to leave right now. I'm getting goosebumps.",
  "I can't believe this, it's glowing. I need to get closer.",
  "I can't believe this, I'm not sure what to do. Just keep recording.",
  "Look at that! it looks like it's from another planet. Let me try to touch it.",
  "This is insane. I can't tear my eyes away. This is history.",
  "Are you seeing this? it's absolutely massive. I need to get closer.",
  "What on earth... how is this even possible? I hope it's friendly.",
  "This is insane. it's glowing. Don't make a sound.",
  "I'm shaking right now. it's coming closer. It's so beautiful.",
  "What on earth... is it dangerous? Let me try to touch it.",
  "Quick, record this. it's absolutely massive. Let me try to touch it.",
  "Seriously? did it just make a sound? We have to show someone.",
  "Stay back. I think it's moving. I'm getting goosebumps.",
  "You won't believe what I just found. this is breathtaking. Run!",
  "I'm shaking right now. I have a really bad feeling about this. I hope it's friendly.",
  "Wait, hold on. it looks like it's from another planet. I need to get closer.",
  "I'm shaking right now. it looks like it's from another planet. I'm terrified.",
  "Are you seeing this? we need to leave right now. Let me try to touch it.",
  "I'm shaking right now. did it just make a sound? What do we do?",
  "Hey guys, it's staring right at me. Let's get out of here.",
  "Look at that! I can't tear my eyes away. Let's get out of here.",
  "Are you seeing this? this is going to go viral. It's so beautiful.",
  "Seriously? do you think it sees us? Don't make a sound.",
  "I can't believe this, it's absolutely massive. I hope it's friendly.",
  "I can't believe this, it's absolutely massive. Let's get out of here.",
  "Are you seeing this? this is the craziest thing ever. Let me try to touch it.",
  "Stay back. is it dangerous? I'm terrified.",
  "Hey guys, it's absolutely massive. I hope it's friendly.",
  "Seriously? this is breathtaking. Let's call for help.",
  "I've never seen anything like it. this is going to go viral. This is history.",
  "Hey guys, it's coming closer. What do we do?",
  "Stay back. we need to leave right now. What do we do?",
  "Are you seeing this? I can't tear my eyes away. It's so beautiful.",
  "No way. we need to leave right now. Just keep recording.",
  "This is insane. I have a really bad feeling about this. This is history.",
  "I'm shaking right now. I'm not sure what to do. Let's get out of here.",
  "You won't believe what I just found. do you think it sees us? Just keep recording.",
  "Oh my god, it's absolutely massive. It's so beautiful.",
  "I can't believe this, I think it's moving. Let's get out of here.",
  "Hey guys, this is breathtaking. I'm terrified.",
  "I've never seen anything like it. it's glowing. Let me try to touch it.",
  "You won't believe what I just found. did it just make a sound? We have to show someone.",
  "Oh my god, it's staring right at me. Let me try to touch it.",
  "Seriously? we need to leave right now. I need to get closer.",
  "Look at that! do you think it sees us? Let's get out of here.",
  "Stay back. do you think it sees us? I hope it's friendly.",
  "No way. it looks like it's from another planet. What do we do?",
  "Quick, record this. it's coming closer. Let's call for help.",
  "This changes everything. I think it's moving. Just keep recording.",
  "No way. it's glowing. I'm terrified.",
  "This is insane. it's glowing. I'm getting goosebumps.",
  "I've never seen anything like it. how is this even possible? Don't make a sound.",
  "Oh my god, I'm not sure what to do. I hope it's friendly.",
  "Is this real? is it dangerous? We have to show someone.",
  "Stay back. it's glowing. This is history.",
  "What on earth... it looks like it's from another planet. This is history.",
  "This changes everything. this is breathtaking. I'm terrified.",
  "Hey guys, do you think it sees us? Just keep recording.",
  "This is insane. this is the craziest thing ever. Let's get out of here.",
  "Wait, hold on. is it dangerous? It's so beautiful.",
  "This changes everything. this is the craziest thing ever. I'm terrified.",
  "No way. did it just make a sound? We have to show someone.",
  "Stay back. we need to leave right now. Let's get out of here.",
  "Hey guys, did it just make a sound? Don't make a sound.",
  "This is insane. is it dangerous? Let me try to touch it.",
  "Oh my god, it's glowing. It's so beautiful.",
  "Is this real? this is breathtaking. This is history.",
  "This is insane. this is going to go viral. Let me try to touch it.",
  "This is insane. it's absolutely massive. Just keep recording.",
  "You won't believe what I just found. it's staring right at me. Run!",
  "I can't believe this, this is the craziest thing ever. Let's call for help.",
  "Oh my god, do you think it sees us? Don't make a sound.",
  "Are you seeing this? it's absolutely massive. Don't make a sound.",
  "I've never seen anything like it. did it just make a sound? Let's get out of here.",
  "Oh my god, we need to leave right now. I'm terrified.",
  "Seriously? I can't tear my eyes away. Just keep recording.",
  "What on earth... do you think it sees us? Let's get out of here.",
  "Oh my god, it's glowing. I'm getting goosebumps.",
  "Is this real? I'm not sure what to do. Just keep recording.",
  "Seriously? this shouldn't exist. I need to get closer.",
  "Hey guys, it's glowing. We have to show someone.",
  "Are you seeing this? it's coming closer. It's so beautiful.",
  "Hey guys, I'm not sure what to do. I'm getting goosebumps.",
  "I've never seen anything like it. it's absolutely massive. I need to get closer.",
  "Look at that! it's glowing. Let me try to touch it.",
  "This changes everything. I think it's moving. Let me try to touch it.",
  "I can't believe this, do you think it sees us? Don't make a sound.",
  "No way. it's glowing. It's so beautiful.",
  "Hey guys, did it just make a sound? This is history.",
  "Seriously? this is going to go viral. What do we do?",
  "No way. is it dangerous? I hope it's friendly.",
  "Oh my god, did it just make a sound? I need to get closer.",
  "I'm shaking right now. it's staring right at me. Let's get out of here.",
  "You won't believe what I just found. how is this even possible? Let me try to touch it.",
  "I've never seen anything like it. it's coming closer. What do we do?",
  "Seriously? this is breathtaking. I'm terrified.",
  "Are you seeing this? it's glowing. We have to show someone.",
  "Hey guys, I can't tear my eyes away. I hope it's friendly.",
  "Quick, record this. we need to leave right now. Let's call for help.",
  "Hey guys, I have a really bad feeling about this. What do we do?",
  "Seriously? this is going to go viral. This is history.",
  "I'm shaking right now. I think it's moving. It's so beautiful.",
  "I can't believe this, I think it's moving. Just keep recording.",
  "This is insane. how is this even possible? Let me try to touch it.",
  "Oh my god, I have a really bad feeling about this. I hope it's friendly.",
  "Quick, record this. I'm not sure what to do. Let me try to touch it.",
  "Quick, record this. this is breathtaking. I need to get closer.",
  "Look at that! did it just make a sound? Don't make a sound.",
  "Are you seeing this? I can't tear my eyes away. Let's call for help.",
  "Seriously? I think it's moving. Just keep recording.",
  "Stay back. it's absolutely massive. Let's call for help.",
  "Quick, record this. how is this even possible? We have to show someone.",
  "Oh my god, this shouldn't exist. Let's call for help.",
  "Quick, record this. this shouldn't exist. Let me try to touch it.",
  "I've never seen anything like it. how is this even possible? It's so beautiful.",
  "Seriously? it's glowing. I'm getting goosebumps.",
  "I can't believe this, we need to leave right now. Let's get out of here.",
  "This is insane. it's coming closer. Run!",
  "Quick, record this. I think it's moving. Let's call for help.",
  "No way. do you think it sees us? Let's get out of here.",
  "Stay back. I can't tear my eyes away. Let me try to touch it.",
  "I can't believe this, I can't tear my eyes away. Just keep recording.",
  "No way. it looks like it's from another planet. I hope it's friendly.",
  "Quick, record this. how is this even possible? Don't make a sound.",
  "Are you seeing this? how is this even possible? Let me try to touch it.",
  "Stay back. is it dangerous? I'm getting goosebumps.",
  "I can't believe this, this shouldn't exist. This is history.",
  "Stay back. it's absolutely massive. I'm getting goosebumps.",
  "Quick, record this. do you think it sees us? Let's get out of here.",
  "Is this real? this is going to go viral. What do we do?",
  "I've never seen anything like it. is it dangerous? I'm getting goosebumps.",
  "This changes everything. I can't tear my eyes away. Don't make a sound.",
  "I'm shaking right now. do you think it sees us? I'm terrified.",
  "Are you seeing this? how is this even possible? It's so beautiful.",
  "This changes everything. this is the craziest thing ever. Let's call for help.",
  "I can't believe this, we need to leave right now. I'm terrified.",
  "Oh my god, it's staring right at me. Let's get out of here.",
  "Seriously? we need to leave right now. I'm terrified.",
  "Are you seeing this? I have a really bad feeling about this. Let's call for help.",
  "Wait, hold on. did it just make a sound? Let's call for help.",
  "Stay back. this is the craziest thing ever. I hope it's friendly.",
  "Is this real? it's staring right at me. Let's call for help.",
  "No way. I think it's moving. I'm getting goosebumps.",
  "I'm shaking right now. it's staring right at me. This is history.",
  "Hey guys, it's absolutely massive. Let's get out of here.",
  "Stay back. it's glowing. It's so beautiful.",
  "Wait, hold on. how is this even possible? I'm terrified.",
  "Quick, record this. I can't tear my eyes away. I need to get closer.",
  "Oh my god, it's glowing. I hope it's friendly.",
  "I can't believe this, this is breathtaking. What do we do?",
  "Oh my god, I can't tear my eyes away. I need to get closer.",
  "Wait, hold on. it's staring right at me. Let's get out of here.",
  "What on earth... this is breathtaking. I'm terrified.",
  "I can't believe this, this shouldn't exist. Let me try to touch it.",
  "Wait, hold on. it's staring right at me. What do we do?",
  "You won't believe what I just found. we need to leave right now. I hope it's friendly.",
  "Look at that! this shouldn't exist. I'm getting goosebumps.",
  "Stay back. it's coming closer. Let me try to touch it.",
  "You won't believe what I just found. I have a really bad feeling about this. I'm terrified.",
  "Wait, hold on. it's coming closer. I hope it's friendly.",
  "Oh my god, I think it's moving. What do we do?",
  "Stay back. is it dangerous? I need to get closer.",
  "Is this real? I'm not sure what to do. I'm terrified.",
  "I can't believe this, this shouldn't exist. Don't make a sound.",
  "I can't believe this, we need to leave right now. Don't make a sound.",
  "Seriously? this is going to go viral. I'm terrified.",
  "Seriously? I think it's moving. I'm getting goosebumps.",
  "I've never seen anything like it. I think it's moving. I need to get closer.",
  "No way. we need to leave right now. Let me try to touch it.",
  "What on earth... this shouldn't exist. I'm getting goosebumps.",
  "Look at that! I'm not sure what to do. I'm terrified.",
  "Hey guys, this is breathtaking. Don't make a sound.",
  "Are you seeing this? is it dangerous? I need to get closer.",
  "This changes everything. it's coming closer. I'm terrified.",
  "This is insane. it's glowing. I'm terrified.",
];
