export interface HoroscopePngConfig {
  csvName: string;
  theme: string;
  skipDone: boolean;
  rowStart: number;
  rowEnd: number;
  cardDir: string;
}

export interface HoroscopeCardConfig {
  provider: 'openrouter' | 'kieai';
  model: string;
  apiKey: string;
  theme: string;
  themeDesc: string;
  cardStart: number;
  cardEnd: number;
  skipExisting: boolean;
}

export interface HoroscopeThemeConfig {
  themeName: string;
  nameEn: string;
  cardDir: string;
  accent: string;
  bodyBg: string;
}

const HOROSCOPE_DIR = "/Users/macos/Desktop/ทดสอบว่าทำได้มั้ย/สร้างดวงรายวัน 2";

export function buildHoroscopePngScript(config: HoroscopePngConfig): string {
  const { csvName, theme, skipDone, rowStart, rowEnd, cardDir } = config;

  let script = `#!/bin/bash
# Horoscope PNG Generation Script
# Automatically generated by BulkVideoCreatorApp

# 1. Setup Directory
BASE_DIR="${HOROSCOPE_DIR}"
cd "$BASE_DIR" || { echo "❌ ไม่พบโฟลเดอร์ $BASE_DIR"; exit 1; }

echo "🌟 เริ่มรันโปรแกรมสร้างรูปดวงรายวัน..."
echo "----------------------------------------"

# 2. Build Python Command
CMD="python3 generate_png.py"

${csvName ? `CMD="$CMD --csv \\"${csvName}\\""` : ''}
${theme ? `CMD="$CMD --theme \\"${theme}\\""` : ''}
${cardDir ? `CMD="$CMD --card-dir \\"${cardDir}\\""` : ''}
${skipDone ? `CMD="$CMD --skip-done"` : ''}
${rowStart > 0 && rowEnd > 0 ? `CMD="$CMD --row ${rowStart} ${rowEnd}"` : ''}

echo "Running: $CMD"
eval $CMD

echo "----------------------------------------"
echo "✅ เสร็จสิ้นการทำงาน!"
`;

  return script;
}

export function buildHoroscopeCardScript(config: HoroscopeCardConfig): string {
  const { provider, model, apiKey, theme, themeDesc, cardStart, cardEnd, skipExisting } = config;

  let script = `#!/bin/bash
# Horoscope Card Generation Script
# Automatically generated by BulkVideoCreatorApp

BASE_DIR="${HOROSCOPE_DIR}"
cd "$BASE_DIR" || { echo "❌ ไม่พบโฟลเดอร์ $BASE_DIR"; exit 1; }

echo "🎨 เริ่มรันโปรแกรมสร้างไพ่ AI ($provider)"
echo "----------------------------------------"

cat << 'EOF' > _temp_run_cards.py
import sys, os
from generate_card_set import call_openrouter_full, call_kieai_full, ALL_CARDS, local_filename, build_prompt
from theme_config import get_all_themes, THEMES
from pathlib import Path

provider = "${provider}"
model = "${model}"
api_key = "${apiKey}"
theme_key = "${theme}"
theme_desc_custom = """${themeDesc}"""

script_dir = Path(__file__).parent.resolve()
all_t = get_all_themes(script_dir)
theme = all_t.get(theme_key, THEMES["1"])
theme_desc = theme_desc_custom or "Mystical dark tarot illustration style"
card_dir = script_dir / theme["card_dir"]
card_dir.mkdir(exist_ok=True)

gen_fn = call_kieai_full if provider == "kieai" else call_openrouter_full

print(f"📁 บันทึกที่: {card_dir}")
ok = 0
start_idx = max(0, ${cardStart} - 1)
end_idx = min(78, ${cardEnd})
target_cards = ALL_CARDS[start_idx:end_idx]
skip_existing = ${skipExisting ? 'True' : 'False'}

for i, card in enumerate(target_cards, start_idx + 1):
    fname = local_filename(card)
    save_path = card_dir / fname
    if skip_existing and save_path.exists() and save_path.stat().st_size > 1000:
        print(f" ✓ [{i}/78] ข้าม มีแล้ว: {card}")
        continue
        
    print(f" ⏳ [{i}/78] สร้าง {card}...")
    prompt = build_prompt(card, theme_desc)
    try:
        if gen_fn(prompt, api_key, model, save_path):
            print("   ✅ สำเร็จ")
            ok += 1
        else:
            print("   ❌ ล้มเหลว")
    except Exception as e:
        print(f"   ❌ ล้มเหลว: {e}")

print(f"✨ เสร็จสิ้น! สร้างใหม่ {ok} ใบ")
EOF

python3 _temp_run_cards.py
rm _temp_run_cards.py

echo "----------------------------------------"
echo "✅ เสร็จสิ้น!"
`;

  return script;
}

export function buildHoroscopeDownloadScript(): string {
  return `#!/bin/bash
# Horoscope Download Classic Cards Script
# Automatically generated by BulkVideoCreatorApp

BASE_DIR="${HOROSCOPE_DIR}"
cd "$BASE_DIR" || { echo "❌ ไม่พบโฟลเดอร์ $BASE_DIR"; exit 1; }

echo "⬇️ เริ่มรันโปรแกรมดาวน์โหลดไพ่ทาโรต์ดั้งเดิม..."
echo "----------------------------------------"

python3 download_cards.py

echo "----------------------------------------"
echo "✅ เสร็จสิ้น!"
`;
}

export function buildHoroscopeThemeScript(config: HoroscopeThemeConfig): string {
  const { themeName, nameEn, cardDir, accent, bodyBg } = config;
  
  return `#!/bin/bash
# Horoscope Create Custom Theme Script
# Automatically generated by BulkVideoCreatorApp

BASE_DIR="${HOROSCOPE_DIR}"
cd "$BASE_DIR" || { echo "❌ ไม่พบโฟลเดอร์ $BASE_DIR"; exit 1; }

echo "🎭 เริ่มสร้างธีมใหม่: ${themeName}"
echo "----------------------------------------"

cat << 'EOF' > _temp_run_theme.py
import sys, os
from theme_config import get_all_themes, save_custom_theme, _next_custom_key
from pathlib import Path

script_dir = Path(__file__).parent.resolve()

theme_data = {
    "name": "${themeName}",
    "name_en": "${nameEn}",
    "card_dir": "${cardDir}",
    "desc": "${themeName}",
    "vars": {
        "--accent": "${accent}",
        "--body-bg": "${bodyBg}"
    }
}

key = _next_custom_key(script_dir)
save_custom_theme(script_dir, key, theme_data)

print(f"✅ บันทึกธีม {key} ('{theme_data['name']}') ลงใน custom_themes.json แล้ว!")
print(f"คุณสามารถเรียกใช้มันได้โดยระบุพิมพ์ --theme {key} ในสคริปต์หลัก")
EOF

python3 _temp_run_theme.py
rm _temp_run_theme.py

echo "----------------------------------------"
echo "✅ เสร็จสิ้น!"
`;
}
